"""Seed script — loads the 1000 most common English words into PostgreSQL.

Run via:  verb-trainer vocab-seed
"""

from sqlalchemy.orm import Session

# fmt: off
VOCABULARY_WORDS = [
    # ── 1. Pronouns & Determiners (80 words) ──────────────────────────────
    ("I", "yo", "Pronouns & Determiners"),
    ("you", "tu / usted", "Pronouns & Determiners"),
    ("he", "el", "Pronouns & Determiners"),
    ("she", "ella", "Pronouns & Determiners"),
    ("it", "eso / ello", "Pronouns & Determiners"),
    ("we", "nosotros", "Pronouns & Determiners"),
    ("they", "ellos", "Pronouns & Determiners"),
    ("me", "me / a mi", "Pronouns & Determiners"),
    ("him", "le / a el", "Pronouns & Determiners"),
    ("her", "le / a ella", "Pronouns & Determiners"),
    ("us", "nos", "Pronouns & Determiners"),
    ("them", "les / a ellos", "Pronouns & Determiners"),
    ("my", "mi (posesivo)", "Pronouns & Determiners"),
    ("your", "tu / su (posesivo)", "Pronouns & Determiners"),
    ("his", "su (de el)", "Pronouns & Determiners"),
    ("its", "su (de eso)", "Pronouns & Determiners"),
    ("our", "nuestro", "Pronouns & Determiners"),
    ("their", "su (de ellos)", "Pronouns & Determiners"),
    ("mine", "mio", "Pronouns & Determiners"),
    ("yours", "tuyo / suyo", "Pronouns & Determiners"),
    ("hers", "suyo (de ella)", "Pronouns & Determiners"),
    ("ours", "nuestro (posesivo)", "Pronouns & Determiners"),
    ("theirs", "suyo (de ellos)", "Pronouns & Determiners"),
    ("this", "este / esta", "Pronouns & Determiners"),
    ("that", "ese / esa / aquel", "Pronouns & Determiners"),
    ("these", "estos / estas", "Pronouns & Determiners"),
    ("those", "esos / aquellas", "Pronouns & Determiners"),
    ("the", "el / la / los / las", "Pronouns & Determiners"),
    ("a", "un / una", "Pronouns & Determiners"),
    ("an", "un / una (antes de vocal)", "Pronouns & Determiners"),
    ("some", "algun / algunos", "Pronouns & Determiners"),
    ("any", "cualquier / alguno", "Pronouns & Determiners"),
    ("all", "todo / todos", "Pronouns & Determiners"),
    ("each", "cada uno", "Pronouns & Determiners"),
    ("every", "cada / todo", "Pronouns & Determiners"),
    ("both", "ambos", "Pronouns & Determiners"),
    ("either", "cualquiera (de dos)", "Pronouns & Determiners"),
    ("neither", "ninguno (de dos)", "Pronouns & Determiners"),
    ("another", "otro", "Pronouns & Determiners"),
    ("other", "otro / otra", "Pronouns & Determiners"),
    ("others", "otros / otras", "Pronouns & Determiners"),
    ("such", "tal / semejante", "Pronouns & Determiners"),
    ("no", "no / ningun", "Pronouns & Determiners"),
    ("none", "ninguno", "Pronouns & Determiners"),
    ("myself", "yo mismo", "Pronouns & Determiners"),
    ("yourself", "tu mismo", "Pronouns & Determiners"),
    ("himself", "el mismo", "Pronouns & Determiners"),
    ("herself", "ella misma", "Pronouns & Determiners"),
    ("itself", "si mismo (cosa)", "Pronouns & Determiners"),
    ("ourselves", "nosotros mismos", "Pronouns & Determiners"),
    ("themselves", "ellos mismos", "Pronouns & Determiners"),
    ("who", "quien", "Pronouns & Determiners"),
    ("whom", "a quien", "Pronouns & Determiners"),
    ("whose", "de quien", "Pronouns & Determiners"),
    ("which", "cual / que", "Pronouns & Determiners"),
    ("what", "que / cual", "Pronouns & Determiners"),
    ("whatever", "lo que sea", "Pronouns & Determiners"),
    ("whoever", "quien sea", "Pronouns & Determiners"),
    ("whichever", "cualquiera que", "Pronouns & Determiners"),
    ("something", "algo", "Pronouns & Determiners"),
    ("anything", "cualquier cosa", "Pronouns & Determiners"),
    ("everything", "todo", "Pronouns & Determiners"),
    ("nothing", "nada", "Pronouns & Determiners"),
    ("someone", "alguien", "Pronouns & Determiners"),
    ("anyone", "cualquiera", "Pronouns & Determiners"),
    ("everyone", "todos", "Pronouns & Determiners"),
    ("no one", "nadie", "Pronouns & Determiners"),
    ("somebody", "alguien", "Pronouns & Determiners"),
    ("anybody", "cualquiera", "Pronouns & Determiners"),
    ("everybody", "todos", "Pronouns & Determiners"),
    ("nobody", "nadie", "Pronouns & Determiners"),
    ("several", "varios", "Pronouns & Determiners"),
    ("few", "pocos", "Pronouns & Determiners"),
    ("many", "muchos", "Pronouns & Determiners"),
    ("much", "mucho", "Pronouns & Determiners"),
    ("more", "mas", "Pronouns & Determiners"),
    ("most", "la mayoria", "Pronouns & Determiners"),
    ("less", "menos", "Pronouns & Determiners"),
    ("least", "el minimo", "Pronouns & Determiners"),
    ("enough", "suficiente", "Pronouns & Determiners"),

    # ── 2. Prepositions (60 words) ────────────────────────────────────────
    ("in", "en / dentro de", "Prepositions"),
    ("on", "en / sobre", "Prepositions"),
    ("at", "en / a", "Prepositions"),
    ("to", "a / hacia", "Prepositions"),
    ("from", "desde / de", "Prepositions"),
    ("with", "con", "Prepositions"),
    ("without", "sin", "Prepositions"),
    ("for", "para / por", "Prepositions"),
    ("about", "sobre / acerca de", "Prepositions"),
    ("by", "por / junto a", "Prepositions"),
    ("through", "a traves de", "Prepositions"),
    ("during", "durante", "Prepositions"),
    ("before", "antes de", "Prepositions"),
    ("after", "despues de", "Prepositions"),
    ("above", "arriba de / sobre", "Prepositions"),
    ("below", "abajo de / debajo", "Prepositions"),
    ("under", "debajo de", "Prepositions"),
    ("over", "sobre / encima de", "Prepositions"),
    ("between", "entre (dos)", "Prepositions"),
    ("among", "entre (varios)", "Prepositions"),
    ("into", "hacia dentro de", "Prepositions"),
    ("onto", "sobre / encima de", "Prepositions"),
    ("within", "dentro de", "Prepositions"),
    ("outside", "fuera de", "Prepositions"),
    ("inside", "dentro de", "Prepositions"),
    ("near", "cerca de", "Prepositions"),
    ("beside", "al lado de", "Prepositions"),
    ("behind", "detras de", "Prepositions"),
    ("in front of", "enfrente de", "Prepositions"),
    ("next to", "junto a", "Prepositions"),
    ("across", "al otro lado de", "Prepositions"),
    ("along", "a lo largo de", "Prepositions"),
    ("around", "alrededor de", "Prepositions"),
    ("against", "contra", "Prepositions"),
    ("toward", "hacia", "Prepositions"),
    ("towards", "hacia", "Prepositions"),
    ("upon", "sobre / encima de", "Prepositions"),
    ("beyond", "mas alla de", "Prepositions"),
    ("since", "desde (tiempo)", "Prepositions"),
    ("until", "hasta", "Prepositions"),
    ("up", "arriba / hacia arriba", "Prepositions"),
    ("down", "abajo / hacia abajo", "Prepositions"),
    ("off", "fuera de / lejos de", "Prepositions"),
    ("out", "fuera de", "Prepositions"),
    ("throughout", "a lo largo de", "Prepositions"),
    ("amongst", "entre (varios)", "Prepositions"),
    ("amid", "en medio de", "Prepositions"),
    ("beneath", "debajo de", "Prepositions"),
    ("besides", "ademas de", "Prepositions"),
    ("except", "excepto", "Prepositions"),
    ("including", "incluyendo", "Prepositions"),
    ("regarding", "respecto a", "Prepositions"),
    ("concerning", "con respecto a", "Prepositions"),
    ("despite", "a pesar de", "Prepositions"),
    ("unlike", "a diferencia de", "Prepositions"),
    ("per", "por / segun", "Prepositions"),
    ("via", "via / por medio de", "Prepositions"),
    ("plus", "mas / ademas de", "Prepositions"),
    ("minus", "menos", "Prepositions"),
    ("past", "mas alla de", "Prepositions"),

    # ── 3. Conjunctions & Connectors (50 words) ───────────────────────────
    ("and", "y", "Conjunctions & Connectors"),
    ("but", "pero", "Conjunctions & Connectors"),
    ("or", "o", "Conjunctions & Connectors"),
    ("so", "asi que / entonces", "Conjunctions & Connectors"),
    ("because", "porque", "Conjunctions & Connectors"),
    ("if", "si (condicional)", "Conjunctions & Connectors"),
    ("when", "cuando", "Conjunctions & Connectors"),
    ("while", "mientras", "Conjunctions & Connectors"),
    ("although", "aunque", "Conjunctions & Connectors"),
    ("however", "sin embargo", "Conjunctions & Connectors"),
    ("therefore", "por lo tanto", "Conjunctions & Connectors"),
    ("moreover", "ademas", "Conjunctions & Connectors"),
    ("nevertheless", "no obstante", "Conjunctions & Connectors"),
    ("otherwise", "de lo contrario", "Conjunctions & Connectors"),
    ("unless", "a menos que", "Conjunctions & Connectors"),
    ("since", "ya que / puesto que", "Conjunctions & Connectors"),
    ("until", "hasta que", "Conjunctions & Connectors"),
    ("whether", "si (duda)", "Conjunctions & Connectors"),
    ("whereas", "mientras que", "Conjunctions & Connectors"),
    ("wherever", "donde sea que", "Conjunctions & Connectors"),
    ("whenever", "cuando sea que", "Conjunctions & Connectors"),
    ("whatever", "lo que sea", "Conjunctions & Connectors"),
    ("wherever", "dondequiera", "Conjunctions & Connectors"),
    ("furthermore", "ademas", "Conjunctions & Connectors"),
    ("consequently", "en consecuencia", "Conjunctions & Connectors"),
    ("nonetheless", "no obstante", "Conjunctions & Connectors"),
    ("meanwhile", "mientras tanto", "Conjunctions & Connectors"),
    ("instead", "en vez de", "Conjunctions & Connectors"),
    ("besides", "ademas", "Conjunctions & Connectors"),
    ("yet", "aun / todavia", "Conjunctions & Connectors"),
    ("still", "todavia", "Conjunctions & Connectors"),
    ("then", "entonces / luego", "Conjunctions & Connectors"),
    ("thus", "asi / de este modo", "Conjunctions & Connectors"),
    ("hence", "por eso", "Conjunctions & Connectors"),
    ("likewise", "de igual manera", "Conjunctions & Connectors"),
    ("similarly", "similarmente", "Conjunctions & Connectors"),
    ("also", "tambien", "Conjunctions & Connectors"),
    ("too", "tambien", "Conjunctions & Connectors"),
    ("either", "tampoco", "Conjunctions & Connectors"),
    ("nor", "ni", "Conjunctions & Connectors"),
    ("not only...but also", "no solo...sino tambien", "Conjunctions & Connectors"),
    ("as soon as", "tan pronto como", "Conjunctions & Connectors"),
    ("as long as", "siempre y cuando", "Conjunctions & Connectors"),
    ("even though", "aunque", "Conjunctions & Connectors"),
    ("even if", "incluso si", "Conjunctions & Connectors"),
    ("in order to", "para / con el fin de", "Conjunctions & Connectors"),
    ("so that", "para que", "Conjunctions & Connectors"),
    ("in case", "en caso de que", "Conjunctions & Connectors"),
    ("as if", "como si", "Conjunctions & Connectors"),
    ("rather than", "en lugar de", "Conjunctions & Connectors"),

    # ── 4. Common Verbs (regular only, 200 words) ─────────────────────────
    ("ask", "preguntar / pedir", "Common Verbs"),
    ("answer", "responder / contestar", "Common Verbs"),
    ("call", "llamar", "Common Verbs"),
    ("carry", "llevar / cargar", "Common Verbs"),
    ("change", "cambiar", "Common Verbs"),
    ("check", "verificar / revisar", "Common Verbs"),
    ("clean", "limpiar", "Common Verbs"),
    ("close", "cerrar", "Common Verbs"),
    ("cook", "cocinar", "Common Verbs"),
    ("copy", "copiar", "Common Verbs"),
    ("count", "contar", "Common Verbs"),
    ("cover", "cubrir", "Common Verbs"),
    ("cross", "cruzar", "Common Verbs"),
    ("dance", "bailar", "Common Verbs"),
    ("decide", "decidir", "Common Verbs"),
    ("deliver", "entregar", "Common Verbs"),
    ("describe", "describir", "Common Verbs"),
    ("develop", "desarrollar", "Common Verbs"),
    ("die", "morir", "Common Verbs"),
    ("disappear", "desaparecer", "Common Verbs"),
    ("discover", "descubrir", "Common Verbs"),
    ("discuss", "discutir / conversar", "Common Verbs"),
    ("enjoy", "disfrutar", "Common Verbs"),
    ("enter", "entrar", "Common Verbs"),
    ("explain", "explicar", "Common Verbs"),
    ("explore", "explorar", "Common Verbs"),
    ("express", "expresar", "Common Verbs"),
    ("fail", "fallar / fracasar", "Common Verbs"),
    ("finish", "terminar / finalizar", "Common Verbs"),
    ("follow", "seguir", "Common Verbs"),
    ("force", "forzar / obligar", "Common Verbs"),
    ("gather", "reunir / juntar", "Common Verbs"),
    ("happen", "suceder / pasar", "Common Verbs"),
    ("help", "ayudar", "Common Verbs"),
    ("hope", "esperar", "Common Verbs"),
    ("hurry", "apurarse", "Common Verbs"),
    ("imagine", "imaginar", "Common Verbs"),
    ("improve", "mejorar", "Common Verbs"),
    ("include", "incluir", "Common Verbs"),
    ("increase", "aumentar", "Common Verbs"),
    ("influence", "influir", "Common Verbs"),
    ("inform", "informar", "Common Verbs"),
    ("invite", "invitar", "Common Verbs"),
    ("join", "unirse / juntarse", "Common Verbs"),
    ("jump", "saltar", "Common Verbs"),
    ("kill", "matar", "Common Verbs"),
    ("knock", "golpear / llamar (puerta)", "Common Verbs"),
    ("laugh", "reir", "Common Verbs"),
    ("lie", "mentir / acostarse", "Common Verbs"),
    ("listen", "escuchar", "Common Verbs"),
    ("live", "vivir", "Common Verbs"),
    ("lock", "cerrar con llave", "Common Verbs"),
    ("look", "mirar / parecer", "Common Verbs"),
    ("love", "amar / querer", "Common Verbs"),
    ("manage", "manejar / gestionar", "Common Verbs"),
    ("mark", "marcar", "Common Verbs"),
    ("match", "coincidir / igualar", "Common Verbs"),
    ("matter", "importar / importar", "Common Verbs"),
    ("measure", "medir", "Common Verbs"),
    ("mention", "mencionar", "Common Verbs"),
    ("miss", "extrañar / perderse", "Common Verbs"),
    ("mix", "mezclar", "Common Verbs"),
    ("move", "mover / mudarse", "Common Verbs"),
    ("need", "necesitar", "Common Verbs"),
    ("notice", "notar / darse cuenta", "Common Verbs"),
    ("offer", "ofrecer", "Common Verbs"),
    ("open", "abrir", "Common Verbs"),
    ("order", "ordenar / pedir", "Common Verbs"),
    ("own", "poseer / ser dueno de", "Common Verbs"),
    ("paint", "pintar", "Common Verbs"),
    ("park", "estacionar", "Common Verbs"),
    ("pass", "pasar", "Common Verbs"),
    ("plan", "planear / planificar", "Common Verbs"),
    ("play", "jugar / tocar (instrumento)", "Common Verbs"),
    ("point", "senalar / apuntar", "Common Verbs"),
    ("practice", "practicar", "Common Verbs"),
    ("prepare", "preparar", "Common Verbs"),
    ("present", "presentar", "Common Verbs"),
    ("press", "presionar", "Common Verbs"),
    ("prevent", "prevenir", "Common Verbs"),
    ("produce", "producir", "Common Verbs"),
    ("promise", "prometer", "Common Verbs"),
    ("protect", "proteger", "Common Verbs"),
    ("prove", "probar / demostrar", "Common Verbs"),
    ("provide", "proveer / proporcionar", "Common Verbs"),
    ("pull", "jalar / tirar", "Common Verbs"),
    ("push", "empujar", "Common Verbs"),
    ("raise", "levantar / criar", "Common Verbs"),
    ("reach", "alcanzar / llegar a", "Common Verbs"),
    ("realize", "darse cuenta / realizar", "Common Verbs"),
    ("receive", "recibir", "Common Verbs"),
    ("recognize", "reconocer", "Common Verbs"),
    ("recommend", "recomendar", "Common Verbs"),
    ("record", "grabar / registrar", "Common Verbs"),
    ("reduce", "reducir", "Common Verbs"),
    ("refuse", "rechazar / negarse", "Common Verbs"),
    ("remember", "recordar / acordarse", "Common Verbs"),
    ("remove", "remover / quitar", "Common Verbs"),
    ("repeat", "repetir", "Common Verbs"),
    ("replace", "reemplazar", "Common Verbs"),
    ("reply", "responder / contestar", "Common Verbs"),
    ("report", "reportar / informar", "Common Verbs"),
    ("require", "requerir", "Common Verbs"),
    ("rest", "descansar", "Common Verbs"),
    ("return", "regresar / devolver", "Common Verbs"),
    ("reveal", "revelar", "Common Verbs"),
    ("review", "revisar / repasar", "Common Verbs"),
    ("risk", "arriesgar", "Common Verbs"),
    ("roll", "rodar / enrollar", "Common Verbs"),
    ("save", "ahorrar / guardar / salvar", "Common Verbs"),
    ("search", "buscar", "Common Verbs"),
    ("seem", "parecer", "Common Verbs"),
    ("serve", "servir", "Common Verbs"),
    ("settle", "resolver / establecerse", "Common Verbs"),
    ("share", "compartir", "Common Verbs"),
    ("shout", "gritar", "Common Verbs"),
    ("sign", "firmar / senal", "Common Verbs"),
    ("smile", "sonreir", "Common Verbs"),
    ("solve", "resolver", "Common Verbs"),
    ("sort", "ordenar / clasificar", "Common Verbs"),
    ("start", "empezar / comenzar", "Common Verbs"),
    ("stay", "quedarse / permanecer", "Common Verbs"),
    ("stop", "parar / detener", "Common Verbs"),
    ("study", "estudiar", "Common Verbs"),
    ("succeed", "tener exito", "Common Verbs"),
    ("suggest", "sugerir", "Common Verbs"),
    ("support", "apoyar / soportar", "Common Verbs"),
    ("suppose", "suponer", "Common Verbs"),
    ("surprise", "sorprender", "Common Verbs"),
    ("survive", "sobrevivir", "Common Verbs"),
    ("talk", "hablar / conversar", "Common Verbs"),
    ("taste", "probar / saborear", "Common Verbs"),
    ("thank", "agradecer", "Common Verbs"),
    ("touch", "tocar", "Common Verbs"),
    ("train", "entrenar / capacitar", "Common Verbs"),
    ("travel", "viajar", "Common Verbs"),
    ("try", "intentar / probar", "Common Verbs"),
    ("turn", "girar / volver", "Common Verbs"),
    ("use", "usar / utilizar", "Common Verbs"),
    ("visit", "visitar", "Common Verbs"),
    ("wait", "esperar", "Common Verbs"),
    ("walk", "caminar / andar", "Common Verbs"),
    ("want", "querer / desear", "Common Verbs"),
    ("warn", "advertir", "Common Verbs"),
    ("wash", "lavar", "Common Verbs"),
    ("watch", "mirar / observar", "Common Verbs"),
    ("wonder", "preguntarse / maravillarse", "Common Verbs"),
    ("work", "trabajar", "Common Verbs"),
    ("worry", "preocuparse", "Common Verbs"),
    ("accept", "aceptar", "Common Verbs"),
    ("achieve", "lograr / alcanzar", "Common Verbs"),
    ("add", "agregar / sumar", "Common Verbs"),
    ("admire", "admirar", "Common Verbs"),
    ("admit", "admitir", "Common Verbs"),
    ("afford", "permitirse / tener dinero para", "Common Verbs"),
    ("agree", "estar de acuerdo", "Common Verbs"),
    ("allow", "permitir", "Common Verbs"),
    ("appear", "aparecer / parecer", "Common Verbs"),
    ("apply", "aplicar / solicitar", "Common Verbs"),
    ("argue", "discutir / argumentar", "Common Verbs"),
    ("arrange", "organizar / arreglar", "Common Verbs"),
    ("arrive", "llegar", "Common Verbs"),
    ("avoid", "evitar", "Common Verbs"),
    ("believe", "creer", "Common Verbs"),
    ("belong", "pertenecer", "Common Verbs"),
    ("blame", "culpar", "Common Verbs"),
    ("bother", "molestar", "Common Verbs"),
    ("borrow", "pedir prestado", "Common Verbs"),
    ("claim", "afirmar / reclamar", "Common Verbs"),
    ("compare", "comparar", "Common Verbs"),
    ("complain", "quejarse", "Common Verbs"),
    ("consider", "considerar", "Common Verbs"),
    ("contain", "contener", "Common Verbs"),
    ("continue", "continuar", "Common Verbs"),
    ("create", "crear", "Common Verbs"),
    ("cry", "llorar", "Common Verbs"),
    ("damage", "danar", "Common Verbs"),
    ("dare", "atreverse", "Common Verbs"),
    ("deal", "tratar / repartir", "Common Verbs"),
    ("demand", "exigir", "Common Verbs"),
    ("depend", "depender", "Common Verbs"),
    ("deserve", "merecer", "Common Verbs"),
    ("destroy", "destruir", "Common Verbs"),
    ("determine", "determinar", "Common Verbs"),
    ("disagree", "no estar de acuerdo", "Common Verbs"),
    ("doubt", "dudar", "Common Verbs"),
    ("drop", "dejar caer / soltar", "Common Verbs"),
    ("earn", "ganar (dinero)", "Common Verbs"),
    ("educate", "educar", "Common Verbs"),
    ("employ", "emplear", "Common Verbs"),
    ("encourage", "animar / alentar", "Common Verbs"),
    ("end", "terminar / finalizar", "Common Verbs"),
    ("escape", "escapar", "Common Verbs"),
    ("examine", "examinar", "Common Verbs"),
    ("exist", "existir", "Common Verbs"),
    ("expect", "esperar (anticipar)", "Common Verbs"),
    ("experience", "experimentar", "Common Verbs"),
    ("extend", "extender", "Common Verbs"),
    ("face", "enfrentar", "Common Verbs"),
    ("fix", "arreglar / reparar", "Common Verbs"),
    ("form", "formar", "Common Verbs"),
    ("grab", "agarrar", "Common Verbs"),
    ("guarantee", "garantizar", "Common Verbs"),
    ("guess", "adivinar", "Common Verbs"),
    ("handle", "manejar / manejar", "Common Verbs"),
    ("hate", "odiar", "Common Verbs"),
    ("head", "dirigirse", "Common Verbs"),
    ("identify", "identificar", "Common Verbs"),
    ("ignore", "ignorar", "Common Verbs"),
    ("illustrate", "ilustrar", "Common Verbs"),
    ("intend", "tener la intencion", "Common Verbs"),
    ("introduce", "presentar / introducir", "Common Verbs"),
    ("involve", "involucrar", "Common Verbs"),
    ("lack", "carecer / faltar", "Common Verbs"),
    ("last", "durar", "Common Verbs"),
    ("learn", "aprender", "Common Verbs"),
    ("like", "gustar", "Common Verbs"),
    ("list", "listar / enumerar", "Common Verbs"),
    ("maintain", "mantener", "Common Verbs"),
    ("marry", "casarse", "Common Verbs"),
    ("mind", "importar / molestar", "Common Verbs"),
    ("occur", "ocurrir", "Common Verbs"),
    ("operate", "operar", "Common Verbs"),
    ("organize", "organizar", "Common Verbs"),
    ("participate", "participar", "Common Verbs"),
    ("perform", "realizar / actuar", "Common Verbs"),
    ("pick", "elegir / recoger", "Common Verbs"),
    ("prefer", "preferir", "Common Verbs"),
    ("pretend", "fingir / simular", "Common Verbs"),
    ("print", "imprimir", "Common Verbs"),
    ("progress", "progresar", "Common Verbs"),
    ("propose", "proponer", "Common Verbs"),
    ("publish", "publicar", "Common Verbs"),
    ("punish", "castigar", "Common Verbs"),
    ("pursue", "perseguir", "Common Verbs"),
    ("question", "cuestionar / preguntar", "Common Verbs"),
    ("react", "reaccionar", "Common Verbs"),
    ("recognize", "reconocer", "Common Verbs"),
    ("relax", "relajarse", "Common Verbs"),
    ("remain", "permanecer", "Common Verbs"),
    ("remind", "recordar a alguien", "Common Verbs"),
    ("rent", "alquilar", "Common Verbs"),
    ("repair", "reparar", "Common Verbs"),
    ("respect", "respetar", "Common Verbs"),
    ("respond", "responder", "Common Verbs"),
    ("result", "resultar", "Common Verbs"),
    ("retire", "jubilarse / retirarse", "Common Verbs"),
    ("ride", "montar / andar en", "Common Verbs"),
    ("rush", "apurarse", "Common Verbs"),
    ("satisfy", "satisfacer", "Common Verbs"),
    ("separate", "separar", "Common Verbs"),
    ("shake", "agitar / sacudir", "Common Verbs"),
    ("shape", "dar forma", "Common Verbs"),
    ("shine", "brillar", "Common Verbs"),
    ("shop", "comprar / ir de compras", "Common Verbs"),
    ("signal", "senalizar", "Common Verbs"),
    ("slice", "cortar en rebanadas", "Common Verbs"),
    ("slip", "resbalar / deslizar", "Common Verbs"),
    ("smell", "oler", "Common Verbs"),
    ("snap", "chasquear / romper", "Common Verbs"),
    ("snow", "nevar", "Common Verbs"),
    ("sound", "sonar", "Common Verbs"),
    ("spare", "ahorrar / reservar", "Common Verbs"),
    ("stare", "mirar fijamente", "Common Verbs"),
    ("state", "declarar / afirmar", "Common Verbs"),
    ("step", "pisar / dar un paso", "Common Verbs"),
    ("stick", "pegar / adherir", "Common Verbs"),
    ("store", "almacenar / guardar", "Common Verbs"),
    ("strike", "golpear / hacer huelga", "Common Verbs"),
    ("struggle", "luchar / esforzarse", "Common Verbs"),
    ("submit", "entregar / someter", "Common Verbs"),
    ("suffer", "sufrir", "Common Verbs"),
    ("supply", "suministrar", "Common Verbs"),
    ("suspect", "sospechar", "Common Verbs"),
    ("sweep", "barrer", "Common Verbs"),
    ("switch", "cambiar / interruptor", "Common Verbs"),
    ("target", "apuntar / objetivo", "Common Verbs"),
    ("teach", "ensenar", "Common Verbs"),
    ("tear", "rasgar / lagrima", "Common Verbs"),
    ("test", "probar / examinar", "Common Verbs"),
    ("threaten", "amenazar", "Common Verbs"),
    ("tie", "atar / corbata", "Common Verbs"),
    ("tip", "propina / inclinar", "Common Verbs"),
    ("trace", "rastrear / trazar", "Common Verbs"),
    ("trade", "comerciar / intercambiar", "Common Verbs"),
    ("transfer", "transferir", "Common Verbs"),
    ("transform", "transformar", "Common Verbs"),
    ("translate", "traducir", "Common Verbs"),
    ("transport", "transportar", "Common Verbs"),
    ("trap", "atrapar / trampa", "Common Verbs"),
    ("treat", "tratar", "Common Verbs"),
    ("trust", "confiar", "Common Verbs"),
    ("type", "escribir a maquina / tipo", "Common Verbs"),
    ("unite", "unir", "Common Verbs"),
    ("update", "actualizar", "Common Verbs"),
    ("upset", "molestar / alterar", "Common Verbs"),
    ("urge", "instar / urgir", "Common Verbs"),
    ("value", "valorar", "Common Verbs"),
    ("vary", "variar", "Common Verbs"),
    ("view", "ver / visualizar", "Common Verbs"),
    ("vote", "votar", "Common Verbs"),
    ("weigh", "pesar", "Common Verbs"),
    ("whisper", "susurrar", "Common Verbs"),
    ("wipe", "limpiar / secar", "Common Verbs"),
    ("wish", "desear", "Common Verbs"),
    ("wonder", "preguntarse", "Common Verbs"),
    ("wrap", "envolver", "Common Verbs"),
    ("yell", "gritar", "Common Verbs"),

    # ── 5. Adjectives (150 words) ─────────────────────────────────────────
    ("good", "bueno/a", "Adjectives"),
    ("new", "nuevo/a", "Adjectives"),
    ("first", "primero/a", "Adjectives"),
    ("last", "ultimo/a", "Adjectives"),
    ("long", "largo/a", "Adjectives"),
    ("great", "genial / grande", "Adjectives"),
    ("little", "pequeno/a", "Adjectives"),
    ("own", "propio/a", "Adjectives"),
    ("old", "viejo/a", "Adjectives"),
    ("right", "correcto / derecha", "Adjectives"),
    ("big", "grande", "Adjectives"),
    ("high", "alto/a", "Adjectives"),
    ("different", "diferente", "Adjectives"),
    ("small", "pequeno/a", "Adjectives"),
    ("large", "grande / amplio/a", "Adjectives"),
    ("next", "siguiente / proximo/a", "Adjectives"),
    ("early", "temprano", "Adjectives"),
    ("young", "joven", "Adjectives"),
    ("important", "importante", "Adjectives"),
    ("public", "publico/a", "Adjectives"),
    ("bad", "malo/a", "Adjectives"),
    ("same", "mismo/a", "Adjectives"),
    ("able", "capaz / habilidoso", "Adjectives"),
    ("beautiful", "hermoso/a", "Adjectives"),
    ("best", "mejor", "Adjectives"),
    ("better", "mejor (comparativo)", "Adjectives"),
    ("black", "negro/a", "Adjectives"),
    ("blue", "azul", "Adjectives"),
    ("bright", "brillante", "Adjectives"),
    ("busy", "ocupado/a", "Adjectives"),
    ("certain", "cierto / seguro", "Adjectives"),
    ("cheap", "barato/a", "Adjectives"),
    ("clean", "limpio/a", "Adjectives"),
    ("clear", "claro", "Adjectives"),
    ("cold", "frio/a", "Adjectives"),
    ("common", "comun", "Adjectives"),
    ("complete", "completo/a", "Adjectives"),
    ("complex", "complejo/a", "Adjectives"),
    ("cool", "fresco / genial", "Adjectives"),
    ("correct", "correcto/a", "Adjectives"),
    ("dangerous", "peligroso/a", "Adjectives"),
    ("dark", "oscuro/a", "Adjectives"),
    ("dead", "muerto/a", "Adjectives"),
    ("deep", "profundo/a", "Adjectives"),
    ("difficult", "dificil", "Adjectives"),
    ("dirty", "sucio/a", "Adjectives"),
    ("dry", "seco/a", "Adjectives"),
    ("easy", "facil", "Adjectives"),
    ("empty", "vacio/a", "Adjectives"),
    ("enough", "suficiente", "Adjectives"),
    ("expensive", "caro/a", "Adjectives"),
    ("famous", "famoso/a", "Adjectives"),
    ("fast", "rapido/a", "Adjectives"),
    ("fat", "gordo/a", "Adjectives"),
    ("fine", "bien / fino/a", "Adjectives"),
    ("foreign", "extranjero/a", "Adjectives"),
    ("free", "libre / gratis", "Adjectives"),
    ("fresh", "fresco/a", "Adjectives"),
    ("full", "lleno/a", "Adjectives"),
    ("funny", "divertido / gracioso", "Adjectives"),
    ("general", "general", "Adjectives"),
    ("gentle", "suave / amable", "Adjectives"),
    ("glad", "contento / alegre", "Adjectives"),
    ("golden", "dorado/a", "Adjectives"),
    ("green", "verde", "Adjectives"),
    ("happy", "feliz", "Adjectives"),
    ("hard", "duro / dificil", "Adjectives"),
    ("heavy", "pesado/a", "Adjectives"),
    ("helpful", "servicial / util", "Adjectives"),
    ("honest", "honesto/a", "Adjectives"),
    ("hot", "caliente", "Adjectives"),
    ("huge", "enorme", "Adjectives"),
    ("hungry", "hambriento/a", "Adjectives"),
    ("ill", "enfermo/a", "Adjectives"),
    ("kind", "amable", "Adjectives"),
    ("late", "tarde", "Adjectives"),
    ("lazy", "perezoso/a", "Adjectives"),
    ("light", "ligero / claro", "Adjectives"),
    ("likely", "probable", "Adjectives"),
    ("lonely", "solitario/a", "Adjectives"),
    ("lovely", "encantador/a", "Adjectives"),
    ("lucky", "afortunado/a", "Adjectives"),
    ("mad", "loco / enojado", "Adjectives"),
    ("main", "principal", "Adjectives"),
    ("modern", "moderno/a", "Adjectives"),
    ("narrow", "estrecho/a", "Adjectives"),
    ("natural", "natural", "Adjectives"),
    ("nearly", "casi", "Adjectives"),
    ("necessary", "necesario/a", "Adjectives"),
    ("nervous", "nervioso/a", "Adjectives"),
    ("nice", "agradable / bonito", "Adjectives"),
    ("normal", "normal", "Adjectives"),
    ("open", "abierto/a", "Adjectives"),
    ("perfect", "perfecto/a", "Adjectives"),
    ("possible", "posible", "Adjectives"),
    ("poor", "pobre", "Adjectives"),
    ("popular", "popular", "Adjectives"),
    ("powerful", "poderoso/a", "Adjectives"),
    ("pretty", "bonito/a / lindo/a", "Adjectives"),
    ("proud", "orgulloso/a", "Adjectives"),
    ("quick", "rapido/a", "Adjectives"),
    ("quiet", "tranquilo / silencioso", "Adjectives"),
    ("rare", "raro / poco comun", "Adjectives"),
    ("ready", "listo/a", "Adjectives"),
    ("real", "real / verdadero", "Adjectives"),
    ("rich", "rico/a", "Adjectives"),
    ("rough", "aspero / rugoso", "Adjectives"),
    ("round", "redondo/a", "Adjectives"),
    ("safe", "seguro/a", "Adjectives"),
    ("sad", "triste", "Adjectives"),
    ("scared", "asustado/a", "Adjectives"),
    ("serious", "serio/a", "Adjectives"),
    ("sharp", "afilado / agudo", "Adjectives"),
    ("short", "corto / bajo", "Adjectives"),
    ("shy", "timido/a", "Adjectives"),
    ("silent", "silencioso/a", "Adjectives"),
    ("simple", "simple / sencillo", "Adjectives"),
    ("slow", "lento/a", "Adjectives"),
    ("smart", "inteligente / listo", "Adjectives"),
    ("smooth", "suave / liso", "Adjectives"),
    ("soft", "suave / blando", "Adjectives"),
    ("solid", "solido / firme", "Adjectives"),
    ("sorry", "arrepentido / lo siento", "Adjectives"),
    ("special", "especial", "Adjectives"),
    ("square", "cuadrado", "Adjectives"),
    ("strange", "extrano/a", "Adjectives"),
    ("strict", "estricto/a", "Adjectives"),
    ("strong", "fuerte", "Adjectives"),
    ("stupid", "tonto/a", "Adjectives"),
    ("sure", "seguro / cierto", "Adjectives"),
    ("sweet", "dulce", "Adjectives"),
    ("tall", "alto (persona)", "Adjectives"),
    ("terrible", "terrible", "Adjectives"),
    ("thick", "grueso / espeso", "Adjectives"),
    ("thin", "delgado / fino", "Adjectives"),
    ("tidy", "ordenado/a", "Adjectives"),
    ("tight", "apretado / ajustado", "Adjectives"),
    ("tired", "cansado/a", "Adjectives"),
    ("true", "verdadero/a", "Adjectives"),
    ("useful", "util", "Adjectives"),
    ("usual", "habitual / comun", "Adjectives"),
    ("valuable", "valioso/a", "Adjectives"),
    ("warm", "calido / tibio", "Adjectives"),
    ("weak", "debil", "Adjectives"),
    ("wet", "mojado/a", "Adjectives"),
    ("white", "blanco/a", "Adjectives"),
    ("wide", "ancho / amplio", "Adjectives"),
    ("wild", "salvaje", "Adjectives"),
    ("wise", "sabio/a", "Adjectives"),
    ("wonderful", "maravilloso/a", "Adjectives"),
    ("wrong", "equivocado / incorrecto", "Adjectives"),
    ("yellow", "amarillo/a", "Adjectives"),

    # ── 6. Adverbs (100 words) ────────────────────────────────────────────
    ("not", "no", "Adverbs"),
    ("also", "tambien", "Adverbs"),
    ("very", "muy", "Adverbs"),
    ("just", "solo / justo", "Adverbs"),
    ("only", "solamente", "Adverbs"),
    ("even", "incluso / aun", "Adverbs"),
    ("still", "todavia / aun", "Adverbs"),
    ("already", "ya", "Adverbs"),
    ("always", "siempre", "Adverbs"),
    ("never", "nunca", "Adverbs"),
    ("sometimes", "a veces", "Adverbs"),
    ("often", "a menudo", "Adverbs"),
    ("usually", "usualmente", "Adverbs"),
    ("really", "realmente", "Adverbs"),
    ("quite", "bastante", "Adverbs"),
    ("almost", "casi", "Adverbs"),
    ("hardly", "apenas", "Adverbs"),
    ("barely", "apenas", "Adverbs"),
    ("nearly", "casi", "Adverbs"),
    ("exactly", "exactamente", "Adverbs"),
    ("actually", "en realidad", "Adverbs"),
    ("certainly", "ciertamente", "Adverbs"),
    ("probably", "probablemente", "Adverbs"),
    ("possibly", "posiblemente", "Adverbs"),
    ("perhaps", "quizas", "Adverbs"),
    ("maybe", "tal vez", "Adverbs"),
    ("surely", "seguramente", "Adverbs"),
    ("definitely", "definitivamente", "Adverbs"),
    ("obviously", "obviamente", "Adverbs"),
    ("clearly", "claramente", "Adverbs"),
    ("simply", "simplemente", "Adverbs"),
    ("merely", "meramente", "Adverbs"),
    ("especially", "especialmente", "Adverbs"),
    ("particularly", "particularmente", "Adverbs"),
    ("generally", "generalmente", "Adverbs"),
    ("normally", "normalmente", "Adverbs"),
    ("typically", "tipicamente", "Adverbs"),
    ("frequently", "frecuentemente", "Adverbs"),
    ("rarely", "raramente", "Adverbs"),
    ("seldom", "rara vez", "Adverbs"),
    ("occasionally", "ocasionalmente", "Adverbs"),
    ("regularly", "regularmente", "Adverbs"),
    ("constantly", "constantemente", "Adverbs"),
    ("continuously", "continuamente", "Adverbs"),
    ("gradually", "gradualmente", "Adverbs"),
    ("suddenly", "de repente", "Adverbs"),
    ("immediately", "inmediatamente", "Adverbs"),
    ("quickly", "rapidamente", "Adverbs"),
    ("slowly", "lentamente", "Adverbs"),
    ("carefully", "cuidadosamente", "Adverbs"),
    ("easily", "facilmente", "Adverbs"),
    ("finally", "finalmente", "Adverbs"),
    ("eventually", "eventualmente", "Adverbs"),
    ("lately", "ultimamente", "Adverbs"),
    ("recently", "recientemente", "Adverbs"),
    ("currently", "actualmente", "Adverbs"),
    ("presently", "presentemente", "Adverbs"),
    ("shortly", "pronto / brevemente", "Adverbs"),
    ("soon", "pronto", "Adverbs"),
    ("early", "temprano", "Adverbs"),
    ("late", "tarde", "Adverbs"),
    ("today", "hoy", "Adverbs"),
    ("tomorrow", "manana", "Adverbs"),
    ("yesterday", "ayer", "Adverbs"),
    ("tonight", "esta noche", "Adverbs"),
    ("now", "ahora", "Adverbs"),
    ("then", "entonces / luego", "Adverbs"),
    ("here", "aqui", "Adverbs"),
    ("there", "alli / alla", "Adverbs"),
    ("everywhere", "en todas partes", "Adverbs"),
    ("nowhere", "en ningun lado", "Adverbs"),
    ("somewhere", "en algun lugar", "Adverbs"),
    ("anywhere", "en cualquier lugar", "Adverbs"),
    ("inside", "dentro", "Adverbs"),
    ("outside", "afuera", "Adverbs"),
    ("upstairs", "arriba (escaleras)", "Adverbs"),
    ("downstairs", "abajo (escaleras)", "Adverbs"),
    ("abroad", "en el extranjero", "Adverbs"),
    ("away", "lejos / fuera", "Adverbs"),
    ("back", "atras / de vuelta", "Adverbs"),
    ("forward", "adelante", "Adverbs"),
    ("ahead", "adelante / delante", "Adverbs"),
    ("together", "juntos", "Adverbs"),
    ("apart", "separados", "Adverbs"),
    ("alone", "solo", "Adverbs"),
    ("well", "bien", "Adverbs"),
    ("badly", "mal", "Adverbs"),
    ("better", "mejor", "Adverbs"),
    ("worse", "peor", "Adverbs"),
    ("best", "lo mejor", "Adverbs"),
    ("worst", "lo peor", "Adverbs"),
    ("enough", "suficientemente", "Adverbs"),
    ("too", "demasiado", "Adverbs"),
    ("rather", "bastante / mas bien", "Adverbs"),
    ("fairly", "bastante / justamente", "Adverbs"),
    ("pretty", "bastante", "Adverbs"),
    ("extremely", "extremadamente", "Adverbs"),
    ("highly", "altamente", "Adverbs"),
    ("deeply", "profundamente", "Adverbs"),
    ("widely", "ampliamente", "Adverbs"),
    ("closely", "estrechamente", "Adverbs"),
    ("seriously", "seriamente", "Adverbs"),
    ("directly", "directamente", "Adverbs"),
    ("absolutely", "absolutamente", "Adverbs"),

    # ── 7. Common Nouns (200 words) ───────────────────────────────────────
    ("time", "tiempo", "Common Nouns"),
    ("person", "persona", "Common Nouns"),
    ("year", "ano", "Common Nouns"),
    ("way", "camino / manera", "Common Nouns"),
    ("day", "dia", "Common Nouns"),
    ("thing", "cosa", "Common Nouns"),
    ("man", "hombre", "Common Nouns"),
    ("woman", "mujer", "Common Nouns"),
    ("world", "mundo", "Common Nouns"),
    ("life", "vida", "Common Nouns"),
    ("hand", "mano", "Common Nouns"),
    ("place", "lugar", "Common Nouns"),
    ("case", "caso", "Common Nouns"),
    ("week", "semana", "Common Nouns"),
    ("company", "empresa", "Common Nouns"),
    ("system", "sistema", "Common Nouns"),
    ("program", "programa", "Common Nouns"),
    ("question", "pregunta", "Common Nouns"),
    ("work", "trabajo", "Common Nouns"),
    ("government", "gobierno", "Common Nouns"),
    ("number", "numero", "Common Nouns"),
    ("night", "noche", "Common Nouns"),
    ("point", "punto", "Common Nouns"),
    ("home", "hogar / casa", "Common Nouns"),
    ("water", "agua", "Common Nouns"),
    ("room", "habitacion", "Common Nouns"),
    ("mother", "madre", "Common Nouns"),
    ("area", "area", "Common Nouns"),
    ("money", "dinero", "Common Nouns"),
    ("story", "historia / cuento", "Common Nouns"),
    ("fact", "hecho", "Common Nouns"),
    ("month", "mes", "Common Nouns"),
    ("lot", "mucho / lote", "Common Nouns"),
    ("right", "derecho", "Common Nouns"),
    ("study", "estudio", "Common Nouns"),
    ("book", "libro", "Common Nouns"),
    ("eye", "ojo", "Common Nouns"),
    ("job", "trabajo / empleo", "Common Nouns"),
    ("word", "palabra", "Common Nouns"),
    ("business", "negocio", "Common Nouns"),
    ("issue", "problema / tema", "Common Nouns"),
    ("side", "lado", "Common Nouns"),
    ("kind", "tipo", "Common Nouns"),
    ("head", "cabeza", "Common Nouns"),
    ("house", "casa", "Common Nouns"),
    ("service", "servicio", "Common Nouns"),
    ("friend", "amigo/a", "Common Nouns"),
    ("father", "padre", "Common Nouns"),
    ("power", "poder", "Common Nouns"),
    ("hour", "hora", "Common Nouns"),
    ("game", "juego", "Common Nouns"),
    ("line", "linea", "Common Nouns"),
    ("end", "fin / final", "Common Nouns"),
    ("member", "miembro", "Common Nouns"),
    ("law", "ley", "Common Nouns"),
    ("car", "auto / coche", "Common Nouns"),
    ("city", "ciudad", "Common Nouns"),
    ("community", "comunidad", "Common Nouns"),
    ("name", "nombre", "Common Nouns"),
    ("president", "presidente", "Common Nouns"),
    ("team", "equipo", "Common Nouns"),
    ("minute", "minuto", "Common Nouns"),
    ("idea", "idea", "Common Nouns"),
    ("body", "cuerpo", "Common Nouns"),
    ("information", "informacion", "Common Nouns"),
    ("food", "comida", "Common Nouns"),
    ("school", "escuela", "Common Nouns"),
    ("family", "familia", "Common Nouns"),
    ("child", "nino/a", "Common Nouns"),
    ("problem", "problema", "Common Nouns"),
    ("group", "grupo", "Common Nouns"),
    ("country", "pais", "Common Nouns"),
    ("student", "estudiante", "Common Nouns"),
    ("teacher", "maestro/a", "Common Nouns"),
    ("doctor", "doctor / medico", "Common Nouns"),
    ("office", "oficina", "Common Nouns"),
    ("table", "mesa", "Common Nouns"),
    ("door", "puerta", "Common Nouns"),
    ("window", "ventana", "Common Nouns"),
    ("street", "calle", "Common Nouns"),
    ("road", "carretera / camino", "Common Nouns"),
    ("floor", "piso / suelo", "Common Nouns"),
    ("wall", "pared", "Common Nouns"),
    ("chair", "silla", "Common Nouns"),
    ("phone", "telefono", "Common Nouns"),
    ("computer", "computadora", "Common Nouns"),
    ("paper", "papel", "Common Nouns"),
    ("letter", "carta / letra", "Common Nouns"),
    ("picture", "foto / imagen", "Common Nouns"),
    ("music", "musica", "Common Nouns"),
    ("movie", "pelicula", "Common Nouns"),
    ("song", "cancion", "Common Nouns"),
    ("color", "color", "Common Nouns"),
    ("language", "idioma / lengua", "Common Nouns"),
    ("country", "pais", "Common Nouns"),
    ("state", "estado", "Common Nouns"),
    ("town", "pueblo", "Common Nouns"),
    ("village", "aldea / pueblo", "Common Nouns"),
    ("market", "mercado", "Common Nouns"),
    ("store", "tienda", "Common Nouns"),
    ("restaurant", "restaurante", "Common Nouns"),
    ("hospital", "hospital", "Common Nouns"),
    ("church", "iglesia", "Common Nouns"),
    ("park", "parque", "Common Nouns"),
    ("garden", "jardin", "Common Nouns"),
    ("farm", "granja", "Common Nouns"),
    ("river", "rio", "Common Nouns"),
    ("mountain", "montana", "Common Nouns"),
    ("sea", "mar", "Common Nouns"),
    ("ocean", "oceano", "Common Nouns"),
    ("lake", "lago", "Common Nouns"),
    ("tree", "arbol", "Common Nouns"),
    ("flower", "flor", "Common Nouns"),
    ("grass", "hierba / cesped", "Common Nouns"),
    ("animal", "animal", "Common Nouns"),
    ("dog", "perro", "Common Nouns"),
    ("cat", "gato", "Common Nouns"),
    ("bird", "pajaro", "Common Nouns"),
    ("fish", "pez / pescado", "Common Nouns"),
    ("horse", "caballo", "Common Nouns"),
    ("cow", "vaca", "Common Nouns"),
    ("chicken", "pollo / gallina", "Common Nouns"),
    ("apple", "manzana", "Common Nouns"),
    ("bread", "pan", "Common Nouns"),
    ("milk", "leche", "Common Nouns"),
    ("coffee", "cafe", "Common Nouns"),
    ("tea", "te", "Common Nouns"),
    ("sugar", "azucar", "Common Nouns"),
    ("salt", "sal", "Common Nouns"),
    ("egg", "huevo", "Common Nouns"),
    ("rice", "arroz", "Common Nouns"),
    ("meat", "carne", "Common Nouns"),
    ("fruit", "fruta", "Common Nouns"),
    ("vegetable", "verdura", "Common Nouns"),
    ("clothes", "ropa", "Common Nouns"),
    ("shirt", "camisa", "Common Nouns"),
    ("shoes", "zapatos", "Common Nouns"),
    ("hat", "sombrero / gorro", "Common Nouns"),
    ("bag", "bolsa / bolso", "Common Nouns"),
    ("key", "llave", "Common Nouns"),
    ("card", "tarjeta", "Common Nouns"),
    ("clock", "reloj", "Common Nouns"),
    ("watch", "reloj de pulsera", "Common Nouns"),
    ("mirror", "espejo", "Common Nouns"),
    ("box", "caja", "Common Nouns"),
    ("bottle", "botella", "Common Nouns"),
    ("cup", "taza", "Common Nouns"),
    ("plate", "plato", "Common Nouns"),
    ("knife", "cuchillo", "Common Nouns"),
    ("fork", "tenedor", "Common Nouns"),
    ("spoon", "cuchara", "Common Nouns"),
    ("pen", "lapicera / boligrafo", "Common Nouns"),
    ("pencil", "lapiz", "Common Nouns"),
    ("desk", "escritorio", "Common Nouns"),
    ("bed", "cama", "Common Nouns"),
    ("sofa", "sofa", "Common Nouns"),
    ("lamp", "lampara", "Common Nouns"),
    ("radio", "radio", "Common Nouns"),
    ("television", "television", "Common Nouns"),
    ("camera", "camara", "Common Nouns"),
    ("newspaper", "periodico", "Common Nouns"),
    ("magazine", "revista", "Common Nouns"),
    ("dictionary", "diccionario", "Common Nouns"),
    ("map", "mapa", "Common Nouns"),
    ("ticket", "boleto / entrada", "Common Nouns"),
    ("passport", "pasaporte", "Common Nouns"),
    ("address", "direccion", "Common Nouns"),
    ("email", "correo electronico", "Common Nouns"),
    ("message", "mensaje", "Common Nouns"),
    ("note", "nota", "Common Nouns"),
    ("report", "reporte / informe", "Common Nouns"),
    ("plan", "plan", "Common Nouns"),
    ("decision", "decision", "Common Nouns"),
    ("reason", "razon / motivo", "Common Nouns"),
    ("result", "resultado", "Common Nouns"),
    ("effect", "efecto", "Common Nouns"),
    ("cause", "causa", "Common Nouns"),
    ("change", "cambio", "Common Nouns"),
    ("difference", "diferencia", "Common Nouns"),
    ("example", "ejemplo", "Common Nouns"),
    ("experience", "experiencia", "Common Nouns"),
    ("knowledge", "conocimiento", "Common Nouns"),
    ("education", "educacion", "Common Nouns"),
    ("health", "salud", "Common Nouns"),
    ("weather", "clima", "Common Nouns"),
    ("sun", "sol", "Common Nouns"),
    ("rain", "lluvia", "Common Nouns"),
    ("snow", "nieve", "Common Nouns"),
    ("wind", "viento", "Common Nouns"),
    ("cloud", "nube", "Common Nouns"),
    ("sky", "cielo", "Common Nouns"),
    ("star", "estrella", "Common Nouns"),
    ("moon", "luna", "Common Nouns"),
    ("earth", "tierra", "Common Nouns"),
    ("fire", "fuego", "Common Nouns"),
    ("ice", "hielo", "Common Nouns"),
    ("stone", "piedra", "Common Nouns"),
    ("metal", "metal", "Common Nouns"),
    ("wood", "madera", "Common Nouns"),
    ("glass", "vidrio / vaso", "Common Nouns"),
    ("air", "aire", "Common Nouns"),
    ("light", "luz", "Common Nouns"),
    ("darkness", "oscuridad", "Common Nouns"),
    ("sound", "sonido", "Common Nouns"),
    ("noise", "ruido", "Common Nouns"),
    ("silence", "silencio", "Common Nouns"),
    ("smell", "olor", "Common Nouns"),
    ("taste", "sabor", "Common Nouns"),
    ("feeling", "sentimiento", "Common Nouns"),
    ("thought", "pensamiento", "Common Nouns"),
    ("dream", "sueno", "Common Nouns"),
    ("hope", "esperanza", "Common Nouns"),
    ("fear", "miedo", "Common Nouns"),
    ("love", "amor", "Common Nouns"),
    ("hate", "odio", "Common Nouns"),
    ("anger", "enojo / ira", "Common Nouns"),
    ("joy", "alegria", "Common Nouns"),
    ("sadness", "tristeza", "Common Nouns"),
    ("pain", "dolor", "Common Nouns"),
    ("peace", "paz", "Common Nouns"),
    ("war", "guerra", "Common Nouns"),
    ("freedom", "libertad", "Common Nouns"),
    ("truth", "verdad", "Common Nouns"),
    ("lie", "mentira", "Common Nouns"),
    ("secret", "secreto", "Common Nouns"),
    ("surprise", "sorpresa", "Common Nouns"),
    ("luck", "suerte", "Common Nouns"),
    ("chance", "oportunidad / posibilidad", "Common Nouns"),
    ("choice", "eleccion", "Common Nouns"),
    ("option", "opcion", "Common Nouns"),
    ("answer", "respuesta", "Common Nouns"),
    ("solution", "solucion", "Common Nouns"),
    ("success", "exito", "Common Nouns"),
    ("failure", "fracaso", "Common Nouns"),
    ("mistake", "error / equivocacion", "Common Nouns"),
    ("accident", "accidente", "Common Nouns"),
    ("danger", "peligro", "Common Nouns"),
    ("safety", "seguridad", "Common Nouns"),
    ("rule", "regla", "Common Nouns"),
    ("order", "orden", "Common Nouns"),
    ("price", "precio", "Common Nouns"),
    ("value", "valor", "Common Nouns"),
    ("cost", "costo", "Common Nouns"),
    ("tax", "impuesto", "Common Nouns"),
    ("debt", "deuda", "Common Nouns"),
    ("profit", "ganancia", "Common Nouns"),
    ("loss", "perdida", "Common Nouns"),
    ("gift", "regalo", "Common Nouns"),
    ("present", "presente / regalo", "Common Nouns"),
    ("party", "fiesta", "Common Nouns"),
    ("holiday", "feriado / vacaciones", "Common Nouns"),
    ("vacation", "vacaciones", "Common Nouns"),
    ("trip", "viaje", "Common Nouns"),
    ("journey", "viaje / travesia", "Common Nouns"),
    ("flight", "vuelo", "Common Nouns"),
    ("train", "tren", "Common Nouns"),
    ("bus", "autobus / colectivo", "Common Nouns"),
    ("ship", "barco", "Common Nouns"),
    ("boat", "bote", "Common Nouns"),
    ("bicycle", "bicicleta", "Common Nouns"),
    ("bridge", "puente", "Common Nouns"),
    ("building", "edificio", "Common Nouns"),
    ("castle", "castillo", "Common Nouns"),
    ("tower", "torre", "Common Nouns"),
    ("roof", "techo", "Common Nouns"),
    ("stairs", "escaleras", "Common Nouns"),
    ("elevator", "ascensor", "Common Nouns"),
    ("hall", "salon / pasillo", "Common Nouns"),
    ("kitchen", "cocina", "Common Nouns"),
    ("bathroom", "bano", "Common Nouns"),
    ("bedroom", "dormitorio", "Common Nouns"),
    ("living room", "sala de estar", "Common Nouns"),
    ("garage", "garaje", "Common Nouns"),
    ("basement", "sotano", "Common Nouns"),
    ("attic", "atico", "Common Nouns"),
    ("fence", "cerca / valla", "Common Nouns"),
    ("gate", "porton / puerta", "Common Nouns"),
    ("path", "sendero / camino", "Common Nouns"),
    ("corner", "esquina", "Common Nouns"),
    ("edge", "borde", "Common Nouns"),
    ("center", "centro", "Common Nouns"),
    ("middle", "medio", "Common Nouns"),
    ("top", "parte superior", "Common Nouns"),
    ("bottom", "parte inferior", "Common Nouns"),
    ("front", "frente", "Common Nouns"),
    ("back", "espalda / atras", "Common Nouns"),
    ("left", "izquierda", "Common Nouns"),
    ("right", "derecha", "Common Nouns"),
    ("north", "norte", "Common Nouns"),
    ("south", "sur", "Common Nouns"),
    ("east", "este", "Common Nouns"),
    ("west", "oeste", "Common Nouns"),
    ("direction", "direccion", "Common Nouns"),
    ("distance", "distancia", "Common Nouns"),
    ("speed", "velocidad", "Common Nouns"),
    ("size", "tamano", "Common Nouns"),
    ("shape", "forma", "Common Nouns"),
    ("weight", "peso", "Common Nouns"),
    ("height", "altura", "Common Nouns"),
    ("length", "longitud", "Common Nouns"),
    ("width", "ancho", "Common Nouns"),
    ("depth", "profundidad", "Common Nouns"),
    ("temperature", "temperatura", "Common Nouns"),
    ("age", "edad", "Common Nouns"),
    ("date", "fecha", "Common Nouns"),
    ("season", "estacion del ano", "Common Nouns"),
    ("spring", "primavera", "Common Nouns"),
    ("summer", "verano", "Common Nouns"),
    ("autumn", "otono", "Common Nouns"),
    ("winter", "invierno", "Common Nouns"),
    ("morning", "manana", "Common Nouns"),
    ("afternoon", "tarde", "Common Nouns"),
    ("evening", "noche / atardecer", "Common Nouns"),
    ("midnight", "medianoche", "Common Nouns"),
    ("noon", "mediodia", "Common Nouns"),
    ("moment", "momento", "Common Nouns"),
    ("period", "periodo", "Common Nouns"),
    ("century", "siglo", "Common Nouns"),
    ("decade", "decada", "Common Nouns"),
    ("past", "pasado", "Common Nouns"),
    ("present", "presente", "Common Nouns"),
    ("future", "futuro", "Common Nouns"),
    ("history", "historia", "Common Nouns"),
    ("culture", "cultura", "Common Nouns"),
    ("tradition", "tradicion", "Common Nouns"),
    ("religion", "religion", "Common Nouns"),
    ("science", "ciencia", "Common Nouns"),
    ("art", "arte", "Common Nouns"),
    ("sport", "deporte", "Common Nouns"),
    ("news", "noticias", "Common Nouns"),
    ("technology", "tecnologia", "Common Nouns"),
    ("internet", "internet", "Common Nouns"),
    ("website", "sitio web", "Common Nouns"),
    ("software", "software", "Common Nouns"),
    ("hardware", "hardware", "Common Nouns"),
    ("screen", "pantalla", "Common Nouns"),
    ("keyboard", "teclado", "Common Nouns"),
    ("mouse", "raton", "Common Nouns"),
    ("battery", "bateria", "Common Nouns"),
    ("cable", "cable", "Common Nouns"),
    ("button", "boton", "Common Nouns"),
    ("switch", "interruptor", "Common Nouns"),
    ("signal", "senal", "Common Nouns"),
    ("network", "red", "Common Nouns"),
    ("connection", "conexion", "Common Nouns"),
    ("password", "contrasena", "Common Nouns"),
    ("account", "cuenta", "Common Nouns"),
    ("profile", "perfil", "Common Nouns"),
    ("photo", "foto", "Common Nouns"),
    ("video", "video", "Common Nouns"),
    ("audio", "audio", "Common Nouns"),
    ("file", "archivo", "Common Nouns"),
    ("folder", "carpeta", "Common Nouns"),
    ("folder", "carpeta", "Common Nouns"),
    ("project", "proyecto", "Common Nouns"),
    ("task", "tarea", "Common Nouns"),
    ("goal", "meta / objetivo", "Common Nouns"),
    ("target", "objetivo / blanco", "Common Nouns"),
    ("purpose", "proposito", "Common Nouns"),
    ("meaning", "significado", "Common Nouns"),
    ("sense", "sentido", "Common Nouns"),
    ("mind", "mente", "Common Nouns"),
    ("brain", "cerebro", "Common Nouns"),
    ("heart", "corazon", "Common Nouns"),
    ("soul", "alma", "Common Nouns"),
    ("spirit", "espiritu", "Common Nouns"),
    ("energy", "energia", "Common Nouns"),
    ("force", "fuerza", "Common Nouns"),
    ("matter", "materia / asunto", "Common Nouns"),
    ("space", "espacio", "Common Nouns"),
    ("universe", "universo", "Common Nouns"),
    ("planet", "planeta", "Common Nouns"),
    ("nature", "naturaleza", "Common Nouns"),
    ("environment", "medio ambiente", "Common Nouns"),
    ("pollution", "contaminacion", "Common Nouns"),
    ("climate", "clima", "Common Nouns"),
    ("population", "poblacion", "Common Nouns"),
    ("society", "sociedad", "Common Nouns"),
    ("community", "comunidad", "Common Nouns"),
    ("neighbor", "vecino/a", "Common Nouns"),
    ("stranger", "extrano / desconocido", "Common Nouns"),
    ("couple", "pareja", "Common Nouns"),
    ("relationship", "relacion", "Common Nouns"),
    ("marriage", "matrimonio", "Common Nouns"),
    ("wedding", "boda", "Common Nouns"),
    ("birthday", "cumpleanos", "Common Nouns"),
    ("anniversary", "aniversario", "Common Nouns"),
    ("funeral", "funeral", "Common Nouns"),
    ("ceremony", "ceremonia", "Common Nouns"),
    ("festival", "festival", "Common Nouns"),
    ("concert", "concierto", "Common Nouns"),
    ("show", "espectaculo", "Common Nouns"),
    ("theater", "teatro", "Common Nouns"),
    ("museum", "museo", "Common Nouns"),
    ("library", "biblioteca", "Common Nouns"),
    ("university", "universidad", "Common Nouns"),
    ("college", "universidad / facultad", "Common Nouns"),
    ("class", "clase", "Common Nouns"),
    ("lesson", "leccion", "Common Nouns"),
    ("exam", "examen", "Common Nouns"),
    ("test", "prueba / examen", "Common Nouns"),
    ("grade", "calificacion / grado", "Common Nouns"),
    ("degree", "titulo / grado", "Common Nouns"),
    ("subject", "materia / tema", "Common Nouns"),
    ("topic", "tema", "Common Nouns"),
    ("detail", "detalle", "Common Nouns"),
    ("part", "parte", "Common Nouns"),
    ("piece", "pieza / trozo", "Common Nouns"),
    ("bit", "poco / trozo", "Common Nouns"),
    ("section", "seccion", "Common Nouns"),
    ("chapter", "capitulo", "Common Nouns"),
    ("page", "pagina", "Common Nouns"),
    ("paragraph", "parrafo", "Common Nouns"),
    ("sentence", "oracion / frase", "Common Nouns"),
    ("title", "titulo", "Common Nouns"),
    ("author", "autor/a", "Common Nouns"),
    ("reader", "lector/a", "Common Nouns"),
    ("writer", "escritor/a", "Common Nouns"),
    ("artist", "artista", "Common Nouns"),
    ("musician", "musico", "Common Nouns"),
    ("actor", "actor / actriz", "Common Nouns"),
    ("director", "director/a", "Common Nouns"),
    ("producer", "productor/a", "Common Nouns"),
    ("manager", "gerente / administrador", "Common Nouns"),
    ("boss", "jefe / jefa", "Common Nouns"),
    ("worker", "trabajador/a", "Common Nouns"),
    ("employee", "empleado/a", "Common Nouns"),
    ("customer", "cliente", "Common Nouns"),
    ("client", "cliente", "Common Nouns"),
    ("visitor", "visitante", "Common Nouns"),
    ("guest", "huesped / invitado", "Common Nouns"),
    ("host", "anfitrion", "Common Nouns"),
    ("leader", "lider", "Common Nouns"),
    ("member", "miembro", "Common Nouns"),
    ("citizen", "ciudadano/a", "Common Nouns"),
    ("human", "humano/a", "Common Nouns"),
    ("creature", "criatura", "Common Nouns"),
    ("species", "especie", "Common Nouns"),
    ("race", "raza", "Common Nouns"),
    ("nation", "nacion", "Common Nouns"),
    ("population", "poblacion", "Common Nouns"),
    ("generation", "generacion", "Common Nouns"),
    ("century", "siglo", "Common Nouns"),
    ("era", "era / epoca", "Common Nouns"),
    ("age", "era / edad", "Common Nouns"),
    ("period", "periodo", "Common Nouns"),
    ("phase", "fase", "Common Nouns"),
    ("stage", "etapa / escenario", "Common Nouns"),
    ("step", "paso", "Common Nouns"),
    ("level", "nivel", "Common Nouns"),
    ("degree", "grado", "Common Nouns"),
    ("rate", "tasa / ritmo", "Common Nouns"),
    ("ratio", "proporcion", "Common Nouns"),
    ("percentage", "porcentaje", "Common Nouns"),
    ("amount", "cantidad", "Common Nouns"),
    ("quantity", "cantidad", "Common Nouns"),
    ("quality", "calidad", "Common Nouns"),
    ("condition", "condicion", "Common Nouns"),
    ("situation", "situacion", "Common Nouns"),
    ("circumstance", "circunstancia", "Common Nouns"),
    ("event", "evento", "Common Nouns"),
    ("incident", "incidente", "Common Nouns"),
    ("occasion", "ocasion", "Common Nouns"),
    ("activity", "actividad", "Common Nouns"),
    ("action", "accion", "Common Nouns"),
    ("behavior", "comportamiento", "Common Nouns"),
    ("habit", "habito", "Common Nouns"),
    ("routine", "rutina", "Common Nouns"),
    ("practice", "practica", "Common Nouns"),
    ("method", "metodo", "Common Nouns"),
    ("technique", "tecnica", "Common Nouns"),
    ("process", "proceso", "Common Nouns"),
    ("procedure", "procedimiento", "Common Nouns"),
    ("strategy", "estrategia", "Common Nouns"),
    ("approach", "enfoque", "Common Nouns"),
    ("style", "estilo", "Common Nouns"),
    ("manner", "manera", "Common Nouns"),
    ("mood", "estado de animo", "Common Nouns"),
    ("attitude", "actitud", "Common Nouns"),
    ("opinion", "opinion", "Common Nouns"),
    ("view", "punto de vista", "Common Nouns"),
    ("belief", "creencia", "Common Nouns"),
    ("faith", "fe", "Common Nouns"),
    ("trust", "confianza", "Common Nouns"),
    ("confidence", "confianza", "Common Nouns"),
    ("respect", "respeto", "Common Nouns"),
    ("admiration", "admiracion", "Common Nouns"),
    ("appreciation", "apreciacion", "Common Nouns"),
    ("gratitude", "gratitud", "Common Nouns"),
    ("sympathy", "simpatia", "Common Nouns"),
    ("empathy", "empatia", "Common Nouns"),
    ("compassion", "compasion", "Common Nouns"),
    ("kindness", "amabilidad", "Common Nouns"),
    ("generosity", "generosidad", "Common Nouns"),
    ("patience", "paciencia", "Common Nouns"),
    ("courage", "coraje", "Common Nouns"),
    ("bravery", "valentia", "Common Nouns"),
    ("strength", "fuerza", "Common Nouns"),
    ("weakness", "debilidad", "Common Nouns"),
    ("skill", "habilidad", "Common Nouns"),
    ("talent", "talento", "Common Nouns"),
    ("ability", "capacidad", "Common Nouns"),
    ("capacity", "capacidad", "Common Nouns"),
    ("potential", "potencial", "Common Nouns"),
    ("opportunity", "oportunidad", "Common Nouns"),
    ("advantage", "ventaja", "Common Nouns"),
    ("disadvantage", "desventaja", "Common Nouns"),
    ("benefit", "beneficio", "Common Nouns"),
    ("reward", "recompensa", "Common Nouns"),
    ("punishment", "castigo", "Common Nouns"),
    ("penalty", "pena / sancion", "Common Nouns"),
    ("fine", "multa", "Common Nouns"),
    ("crime", "crimen / delito", "Common Nouns"),
    ("violence", "violencia", "Common Nouns"),
    ("conflict", "conflicto", "Common Nouns"),
    ("argument", "discusion / argumento", "Common Nouns"),
    ("fight", "pelea", "Common Nouns"),
    ("battle", "batalla", "Common Nouns"),
    ("competition", "competencia", "Common Nouns"),
    ("contest", "concurso", "Common Nouns"),
    ("match", "partido / encuentro", "Common Nouns"),
    ("race", "carrera", "Common Nouns"),
    ("championship", "campeonato", "Common Nouns"),
    ("tournament", "torneo", "Common Nouns"),
    ("medal", "medalla", "Common Nouns"),
    ("trophy", "trofeo", "Common Nouns"),
    ("prize", "premio", "Common Nouns"),
    ("award", "premio / reconocimiento", "Common Nouns"),
    ("honor", "honor", "Common Nouns"),
    ("glory", "gloria", "Common Nouns"),
    ("fame", "fama", "Common Nouns"),
    ("reputation", "reputacion", "Common Nouns"),
    ("image", "imagen", "Common Nouns"),
    ("appearance", "apariencia", "Common Nouns"),
    ("look", "aspecto / mirada", "Common Nouns"),
    ("expression", "expresion", "Common Nouns"),
    ("smile", "sonrisa", "Common Nouns"),
    ("laugh", "risa", "Common Nouns"),
    ("tear", "lagrima", "Common Nouns"),
    ("voice", "voz", "Common Nouns"),
    ("tone", "tono", "Common Nouns"),
    ("accent", "acento", "Common Nouns"),
    ("pronunciation", "pronunciacion", "Common Nouns"),
    ("grammar", "gramatica", "Common Nouns"),
    ("vocabulary", "vocabulario", "Common Nouns"),
    ("sentence", "oracion", "Common Nouns"),
    ("phrase", "frase", "Common Nouns"),
    ("idiom", "modismo", "Common Nouns"),
    ("slang", "jerga", "Common Nouns"),
    ("dialect", "dialecto", "Common Nouns"),
    ("accent", "acento", "Common Nouns"),
    ("conversation", "conversacion", "Common Nouns"),
    ("discussion", "discusion", "Common Nouns"),
    ("debate", "debate", "Common Nouns"),
    ("interview", "entrevista", "Common Nouns"),
    ("speech", "discurso", "Common Nouns"),
    ("presentation", "presentacion", "Common Nouns"),
    ("lecture", "conferencia", "Common Nouns"),
    ("meeting", "reunion", "Common Nouns"),
    ("conference", "conferencia", "Common Nouns"),
    ("seminar", "seminario", "Common Nouns"),
    ("workshop", "taller", "Common Nouns"),
    ("course", "curso", "Common Nouns"),
    ("training", "entrenamiento", "Common Nouns"),
    ("practice", "practica", "Common Nouns"),
    ("exercise", "ejercicio", "Common Nouns"),
    ("drill", "ejercicio / taladro", "Common Nouns"),
    ("homework", "tarea escolar", "Common Nouns"),
    ("assignment", "tarea / asignacion", "Common Nouns"),
    ("project", "proyecto", "Common Nouns"),
    ("research", "investigacion", "Common Nouns"),
    ("experiment", "experimento", "Common Nouns"),
    ("discovery", "descubrimiento", "Common Nouns"),
    ("invention", "invencion", "Common Nouns"),
    ("innovation", "innovacion", "Common Nouns"),
    ("development", "desarrollo", "Common Nouns"),
    ("progress", "progreso", "Common Nouns"),
    ("growth", "crecimiento", "Common Nouns"),
    ("expansion", "expansion", "Common Nouns"),
    ("increase", "aumento", "Common Nouns"),
    ("decrease", "disminucion", "Common Nouns"),
    ("decline", "declive", "Common Nouns"),
    ("improvement", "mejora", "Common Nouns"),
    ("advancement", "avance", "Common Nouns"),
    ("breakthrough", "avance importante", "Common Nouns"),
    ("achievement", "logro", "Common Nouns"),
    ("accomplishment", "realizacion", "Common Nouns"),
    ("contribution", "contribucion", "Common Nouns"),
    ("impact", "impacto", "Common Nouns"),
    ("influence", "influencia", "Common Nouns"),
    ("effect", "efecto", "Common Nouns"),
    ("consequence", "consecuencia", "Common Nouns"),
    ("outcome", "resultado", "Common Nouns"),
    ("result", "resultado", "Common Nouns"),
    ("product", "producto", "Common Nouns"),
    ("result", "resultado", "Common Nouns"),
    ("output", "producto / salida", "Common Nouns"),
    ("input", "entrada / aporte", "Common Nouns"),
    ("source", "fuente", "Common Nouns"),
    ("origin", "origen", "Common Nouns"),
    ("beginning", "comienzo", "Common Nouns"),
    ("start", "inicio", "Common Nouns"),
    ("middle", "medio", "Common Nouns"),
    ("end", "fin", "Common Nouns"),
    ("conclusion", "conclusion", "Common Nouns"),
    ("summary", "resumen", "Common Nouns"),
    ("overview", "vision general", "Common Nouns"),
    ("introduction", "introduccion", "Common Nouns"),
    ("preface", "prefacio", "Common Nouns"),
    ("foreword", "prologo", "Common Nouns"),
    ("appendix", "apendice", "Common Nouns"),
    ("index", "indice", "Common Nouns"),
    ("glossary", "glosario", "Common Nouns"),
    ("reference", "referencia", "Common Nouns"),
    ("citation", "cita", "Common Nouns"),
    ("quote", "cita", "Common Nouns"),
    ("example", "ejemplo", "Common Nouns"),
    ("sample", "muestra", "Common Nouns"),
    ("model", "modelo", "Common Nouns"),
    ("pattern", "patron", "Common Nouns"),
    ("design", "diseno", "Common Nouns"),
    ("plan", "plan", "Common Nouns"),
    ("blueprint", "plano", "Common Nouns"),
    ("sketch", "bosquejo", "Common Nouns"),
    ("drawing", "dibujo", "Common Nouns"),
    ("painting", "pintura", "Common Nouns"),
    ("sculpture", "escultura", "Common Nouns"),
    ("photograph", "fotografia", "Common Nouns"),
    ("portrait", "retrato", "Common Nouns"),
    ("landscape", "paisaje", "Common Nouns"),
    ("scene", "escena", "Common Nouns"),
    ("view", "vista", "Common Nouns"),
    ("sight", "vista / vision", "Common Nouns"),
    ("vision", "vision", "Common Nouns"),
    ("look", "mirada", "Common Nouns"),
    ("glance", "vistazo", "Common Nouns"),
    ("stare", "mirada fija", "Common Nouns"),
    ("gaze", "mirada fija", "Common Nouns"),
    ("peek", "vistazo rapido", "Common Nouns"),
    ("peek", "vistazo rapido", "Common Nouns"),
    ("observation", "observacion", "Common Nouns"),
    ("attention", "atencion", "Common Nouns"),
    ("focus", "enfoque", "Common Nouns"),
    ("concentration", "concentracion", "Common Nouns"),
    ("awareness", "conciencia", "Common Nouns"),
    ("consciousness", "consciencia", "Common Nouns"),
    ("perception", "percepcion", "Common Nouns"),
    ("recognition", "reconocimiento", "Common Nouns"),
    ("understanding", "comprension", "Common Nouns"),
    ("comprehension", "comprension", "Common Nouns"),
    ("insight", "perspectiva", "Common Nouns"),
    ("wisdom", "sabiduria", "Common Nouns"),
    ("intelligence", "inteligencia", "Common Nouns"),
    ("knowledge", "conocimiento", "Common Nouns"),
    ("learning", "aprendizaje", "Common Nouns"),
    ("teaching", "ensenanza", "Common Nouns"),
    ("instruction", "instruccion", "Common Nouns"),
    ("guidance", "orientacion", "Common Nouns"),
    ("advice", "consejo", "Common Nouns"),
    ("suggestion", "sugerencia", "Common Nouns"),
    ("recommendation", "recomendacion", "Common Nouns"),
    ("proposal", "propuesta", "Common Nouns"),
    ("offer", "oferta", "Common Nouns"),
    ("request", "solicitud", "Common Nouns"),
    ("demand", "demanda", "Common Nouns"),
    ("requirement", "requisito", "Common Nouns"),
    ("need", "necesidad", "Common Nouns"),
    ("desire", "deseo", "Common Nouns"),
    ("wish", "deseo", "Common Nouns"),
    ("dream", "sueno", "Common Nouns"),
    ("goal", "meta", "Common Nouns"),
    ("aim", "objetivo", "Common Nouns"),
    ("purpose", "proposito", "Common Nouns"),
    ("intention", "intencion", "Common Nouns"),
    ("motive", "motivo", "Common Nouns"),
    ("motivation", "motivacion", "Common Nouns"),
    ("inspiration", "inspiracion", "Common Nouns"),
    ("encouragement", "aliento", "Common Nouns"),
    ("support", "apoyo", "Common Nouns"),
    ("help", "ayuda", "Common Nouns"),
    ("assistance", "asistencia", "Common Nouns"),
    ("aid", "ayuda / auxilio", "Common Nouns"),
    ("relief", "alivio", "Common Nouns"),
    ("comfort", "consuelo / comodidad", "Common Nouns"),
    ("consolation", "consolacion", "Common Nouns"),
    ("sympathy", "simpatia", "Common Nouns"),
    ("pity", "lastima", "Common Nouns"),
    ("mercy", "misericordia", "Common Nouns"),
    ("forgiveness", "perdon", "Common Nouns"),
    ("apology", "disculpa", "Common Nouns"),
    ("excuse", "excusa", "Common Nouns"),
    ("explanation", "explicacion", "Common Nouns"),
    ("justification", "justificacion", "Common Nouns"),
    ("defense", "defensa", "Common Nouns"),
    ("protection", "proteccion", "Common Nouns"),
    ("security", "seguridad", "Common Nouns"),
    ("insurance", "seguro", "Common Nouns"),
    ("guarantee", "garantia", "Common Nouns"),
    ("warranty", "garantia", "Common Nouns"),
    ("promise", "promesa", "Common Nouns"),
    ("commitment", "compromiso", "Common Nouns"),
    ("obligation", "obligacion", "Common Nouns"),
    ("responsibility", "responsabilidad", "Common Nouns"),
    ("duty", "deber", "Common Nouns"),
    ("task", "tarea", "Common Nouns"),
    ("job", "trabajo", "Common Nouns"),
    ("role", "rol / papel", "Common Nouns"),
    ("function", "funcion", "Common Nouns"),
    ("position", "posicion", "Common Nouns"),
    ("status", "estado", "Common Nouns"),
    ("rank", "rango", "Common Nouns"),
    ("title", "titulo", "Common Nouns"),
    ("name", "nombre", "Common Nouns"),
    ("label", "etiqueta", "Common Nouns"),
    ("tag", "etiqueta", "Common Nouns"),
    ("sign", "senal / letrero", "Common Nouns"),
    ("symbol", "simbolo", "Common Nouns"),
    ("mark", "marca", "Common Nouns"),
    ("indication", "indicacion", "Common Nouns"),
    ("signal", "senal", "Common Nouns"),
    ("warning", "advertencia", "Common Nouns"),
    ("alert", "alerta", "Common Nouns"),
    ("notice", "aviso", "Common Nouns"),
    ("announcement", "anuncio", "Common Nouns"),
    ("declaration", "declaracion", "Common Nouns"),
    ("statement", "declaracion", "Common Nouns"),
    ("claim", "afirmacion", "Common Nouns"),
    ("assertion", "afirmacion", "Common Nouns"),
    ("argument", "argumento", "Common Nouns"),
    ("reason", "razon", "Common Nouns"),
    ("evidence", "evidencia", "Common Nouns"),
    ("proof", "prueba", "Common Nouns"),
    ("fact", "hecho", "Common Nouns"),
    ("truth", "verdad", "Common Nouns"),
    ("reality", "realidad", "Common Nouns"),
    ("fiction", "ficcion", "Common Nouns"),
    ("fantasy", "fantasia", "Common Nouns"),
    ("imagination", "imaginacion", "Common Nouns"),
    ("creativity", "creatividad", "Common Nouns"),
    ("originality", "originalidad", "Common Nouns"),
    ("novelty", "novedad", "Common Nouns"),
    ("uniqueness", "singularidad", "Common Nouns"),
    ("similarity", "similitud", "Common Nouns"),
    ("difference", "diferencia", "Common Nouns"),
    ("contrast", "contraste", "Common Nouns"),
    ("comparison", "comparacion", "Common Nouns"),
    ("analogy", "analogia", "Common Nouns"),
    ("metaphor", "metafora", "Common Nouns"),
    ("simile", "simil", "Common Nouns"),
    ("figure", "figura", "Common Nouns"),
    ("image", "imagen", "Common Nouns"),
    ("picture", "imagen / foto", "Common Nouns"),
    ("illustration", "ilustracion", "Common Nouns"),
    ("diagram", "diagrama", "Common Nouns"),
    ("chart", "grafico", "Common Nouns"),
    ("graph", "grafico", "Common Nouns"),
    ("table", "tabla", "Common Nouns"),
    ("list", "lista", "Common Nouns"),
    ("menu", "menu", "Common Nouns"),
    ("catalog", "catalogo", "Common Nouns"),
    ("directory", "directorio", "Common Nouns"),
    ("register", "registro", "Common Nouns"),
    ("record", "registro", "Common Nouns"),
    ("document", "documento", "Common Nouns"),
    ("file", "archivo", "Common Nouns"),
    ("report", "informe", "Common Nouns"),
    ("summary", "resumen", "Common Nouns"),
    ("abstract", "resumen / abstracto", "Common Nouns"),
    ("outline", "esquema", "Common Nouns"),
    ("draft", "borrador", "Common Nouns"),
    ("version", "version", "Common Nouns"),
    ("edition", "edicion", "Common Nouns"),
    ("copy", "copia", "Common Nouns"),
    ("original", "original", "Common Nouns"),
    ("master", "maestro / original", "Common Nouns"),
    ("backup", "copia de seguridad", "Common Nouns"),
    ("archive", "archivo", "Common Nouns"),
    ("storage", "almacenamiento", "Common Nouns"),
    ("memory", "memoria", "Common Nouns"),
    ("recall", "recuerdo", "Common Nouns"),
    ("remembrance", "recuerdo", "Common Nouns"),
    ("nostalgia", "nostalgia", "Common Nouns"),
    ("reflection", "reflexion", "Common Nouns"),
    ("contemplation", "contemplacion", "Common Nouns"),
    ("meditation", "meditacion", "Common Nouns"),
    ("concentration", "concentracion", "Common Nouns"),
    ("meditation", "meditacion", "Common Nouns"),
    ("relaxation", "relajacion", "Common Nouns"),
    ("rest", "descanso", "Common Nouns"),
    ("pause", "pausa", "Common Nouns"),
    ("break", "descanso / ruptura", "Common Nouns"),
    ("interval", "intervalo", "Common Nouns"),
    ("gap", "brecha / espacio", "Common Nouns"),
    ("space", "espacio", "Common Nouns"),
    ("room", "espacio / habitacion", "Common Nouns"),
    ("area", "area", "Common Nouns"),
    ("zone", "zona", "Common Nouns"),
    ("region", "region", "Common Nouns"),
    ("territory", "territorio", "Common Nouns"),
    ("district", "distrito", "Common Nouns"),
    ("neighborhood", "barrio", "Common Nouns"),
    ("suburb", "suburbio", "Common Nouns"),
    ("outskirts", "afueras", "Common Nouns"),
    ("countryside", "campo", "Common Nouns"),
    ("wilderness", "naturaleza salvaje", "Common Nouns"),
    ("desert", "desierto", "Common Nouns"),
    ("forest", "bosque", "Common Nouns"),
    ("jungle", "selva", "Common Nouns"),
    ("woods", "bosque", "Common Nouns"),
    ("field", "campo", "Common Nouns"),
    ("meadow", "pradera", "Common Nouns"),
    ("pasture", "pastura", "Common Nouns"),
    ("lawn", "cesped", "Common Nouns"),
    ("yard", "patio", "Common Nouns"),
    ("courtyard", "patio interior", "Common Nouns"),
    ("plaza", "plaza", "Common Nouns"),
    ("square", "plaza", "Common Nouns"),
    ("avenue", "avenida", "Common Nouns"),
    ("boulevard", "bulevar", "Common Nouns"),
    ("lane", "callejon / carril", "Common Nouns"),
    ("alley", "callejon", "Common Nouns"),
    ("path", "camino / sendero", "Common Nouns"),
    ("trail", "sendero", "Common Nouns"),
    ("track", "pista / camino", "Common Nouns"),
    ("route", "ruta", "Common Nouns"),
    ("highway", "autopista", "Common Nouns"),
    ("freeway", "autopista", "Common Nouns"),
    ("motorway", "autopista", "Common Nouns"),
    ("expressway", "via rapida", "Common Nouns"),
    ("turnpike", "autopista de peaje", "Common Nouns"),
    ("toll", "peaje", "Common Nouns"),
    ("exit", "salida", "Common Nouns"),
    ("entrance", "entrada", "Common Nouns"),
    ("gate", "porton", "Common Nouns"),
    ("doorway", "umbral", "Common Nouns"),
    ("threshold", "umbral", "Common Nouns"),
    ("porch", "porche", "Common Nouns"),
    ("balcony", "balcon", "Common Nouns"),
    ("terrace", "terraza", "Common Nouns"),
    ("patio", "patio", "Common Nouns"),
    ("deck", "terraza de madera", "Common Nouns"),
    ("veranda", "galeria", "Common Nouns"),
    ("corridor", "corredor", "Common Nouns"),
    ("hallway", "pasillo", "Common Nouns"),
    ("passage", "pasaje", "Common Nouns"),
    ("tunnel", "tunel", "Common Nouns"),
    ("underpass", "paso inferior", "Common Nouns"),
    ("overpass", "paso superior", "Common Nouns"),
    ("intersection", "interseccion", "Common Nouns"),
    ("junction", "cruce", "Common Nouns"),
    ("crossing", "cruce", "Common Nouns"),
    ("roundabout", "rotonda", "Common Nouns"),
    ("traffic", "trafico", "Common Nouns"),
    ("congestion", "congestion", "Common Nouns"),
    ("jam", "embotellamiento", "Common Nouns"),
    ("delay", "retraso", "Common Nouns"),
    ("schedule", "horario", "Common Nouns"),
    ("timetable", "horario", "Common Nouns"),
    ("calendar", "calendario", "Common Nouns"),
    ("agenda", "agenda", "Common Nouns"),
    ("diary", "diario", "Common Nouns"),
    ("journal", "diario / revista", "Common Nouns"),
    ("log", "registro", "Common Nouns"),
    ("blog", "blog", "Common Nouns"),
    ("post", "publicacion", "Common Nouns"),
    ("comment", "comentario", "Common Nouns"),
    ("review", "resena", "Common Nouns"),
    ("rating", "calificacion", "Common Nouns"),
    ("score", "puntaje", "Common Nouns"),
    ("mark", "nota / marca", "Common Nouns"),
    ("grade", "calificacion", "Common Nouns"),
    ("rank", "clasificacion", "Common Nouns"),
    ("position", "posicion", "Common Nouns"),
    ("place", "lugar / posicion", "Common Nouns"),
    ("standing", "posicion / estatus", "Common Nouns"),
    ("reputation", "reputacion", "Common Nouns"),
    ("image", "imagen", "Common Nouns"),
    ("brand", "marca", "Common Nouns"),
    ("logo", "logo", "Common Nouns"),
    ("slogan", "eslogan", "Common Nouns"),
    ("motto", "lema", "Common Nouns"),
    ("theme", "tema", "Common Nouns"),
    ("subject", "tema / materia", "Common Nouns"),
    ("topic", "tema", "Common Nouns"),
    ("issue", "tema / problema", "Common Nouns"),
    ("matter", "asunto", "Common Nouns"),
    ("concern", "preocupacion", "Common Nouns"),
    ("worry", "preocupacion", "Common Nouns"),
    ("anxiety", "ansiedad", "Common Nouns"),
    ("stress", "estres", "Common Nouns"),
    ("tension", "tension", "Common Nouns"),
    ("pressure", "presion", "Common Nouns"),
    ("strain", "esfuerzo / tension", "Common Nouns"),
    ("burden", "carga", "Common Nouns"),
    ("load", "carga", "Common Nouns"),
    ("weight", "peso", "Common Nouns"),
    ("mass", "masa", "Common Nouns"),
    ("volume", "volumen", "Common Nouns"),
    ("density", "densidad", "Common Nouns"),
    ("thickness", "grosor", "Common Nouns"),
    ("width", "ancho", "Common Nouns"),
    ("breadth", "anchura", "Common Nouns"),
    ("length", "longitud", "Common Nouns"),
    ("height", "altura", "Common Nouns"),
    ("depth", "profundidad", "Common Nouns"),
    ("distance", "distancia", "Common Nouns"),
    ("range", "rango / alcance", "Common Nouns"),
    ("scope", "alcance", "Common Nouns"),
    ("extent", "alcance / extension", "Common Nouns"),
    ("scale", "escala", "Common Nouns"),
    ("proportion", "proporcion", "Common Nouns"),
    ("ratio", "proporcion", "Common Nouns"),
    ("fraction", "fraccion", "Common Nouns"),
    ("portion", "porcion", "Common Nouns"),
    ("share", "parte / accion", "Common Nouns"),
    ("slice", "rebanada", "Common Nouns"),
    ("piece", "pieza", "Common Nouns"),
    ("segment", "segmento", "Common Nouns"),
    ("section", "seccion", "Common Nouns"),
    ("division", "division", "Common Nouns"),
    ("department", "departamento", "Common Nouns"),
    ("branch", "rama / sucursal", "Common Nouns"),
    ("office", "oficina", "Common Nouns"),
    ("bureau", "oficina / agencia", "Common Nouns"),
    ("agency", "agencia", "Common Nouns"),
    ("organization", "organizacion", "Common Nouns"),
    ("institution", "institucion", "Common Nouns"),
    ("establishment", "establecimiento", "Common Nouns"),
    ("facility", "instalacion", "Common Nouns"),
    ("plant", "planta / fabrica", "Common Nouns"),
    ("factory", "fabrica", "Common Nouns"),
    ("mill", "molino", "Common Nouns"),
    ("workshop", "taller", "Common Nouns"),
    ("studio", "estudio", "Common Nouns"),
    ("laboratory", "laboratorio", "Common Nouns"),
    ("clinic", "clinica", "Common Nouns"),
    ("pharmacy", "farmacia", "Common Nouns"),
    ("shop", "tienda", "Common Nouns"),
    ("boutique", "boutique", "Common Nouns"),
    ("mall", "centro comercial", "Common Nouns"),
    ("center", "centro", "Common Nouns"),
    ("complex", "complejo", "Common Nouns"),
    ("compound", "compuesto / recinto", "Common Nouns"),
    ("campus", "campus universitario", "Common Nouns"),
    ("station", "estacion", "Common Nouns"),
    ("terminal", "terminal", "Common Nouns"),
    ("airport", "aeropuerto", "Common Nouns"),
    ("harbor", "puerto", "Common Nouns"),
    ("port", "puerto", "Common Nouns"),
    ("dock", "muelle", "Common Nouns"),
    ("pier", "muelle", "Common Nouns"),
    ("wharf", "muelle", "Common Nouns"),
    ("quay", "muelle", "Common Nouns"),
    ("beach", "playa", "Common Nouns"),
    ("shore", "orilla", "Common Nouns"),
    ("coast", "costa", "Common Nouns"),
    ("cliff", "acantilado", "Common Nouns"),
    ("cave", "cueva", "Common Nouns"),
    ("valley", "valle", "Common Nouns"),
    ("hill", "colina", "Common Nouns"),
    ("peak", "cima / pico", "Common Nouns"),
    ("summit", "cima", "Common Nouns"),
    ("slope", "pendiente", "Common Nouns"),
    ("ridge", "cresta", "Common Nouns"),
    ("plateau", "meseta", "Common Nouns"),
    ("plain", "llanura", "Common Nouns"),
    ("prairie", "pradera", "Common Nouns"),
    ("savanna", "sabana", "Common Nouns"),
    ("marsh", "pantano", "Common Nouns"),
    ("swamp", "pantano", "Common Nouns"),
    ("bog", "cienaga", "Common Nouns"),
    ("wetland", "humedal", "Common Nouns"),
    ("island", "isla", "Common Nouns"),
    ("peninsula", "peninsula", "Common Nouns"),
    ("continent", "continente", "Common Nouns"),
    ("hemisphere", "hemisferio", "Common Nouns"),
    ("globe", "globo terraqueo", "Common Nouns"),
    ("sphere", "esfera", "Common Nouns"),
    ("circle", "circulo", "Common Nouns"),
    ("ring", "anillo", "Common Nouns"),
    ("loop", "bucle", "Common Nouns"),
    ("curve", "curva", "Common Nouns"),
    ("arc", "arco", "Common Nouns"),
    ("angle", "angulo", "Common Nouns"),
    ("corner", "esquina", "Common Nouns"),
    ("edge", "borde", "Common Nouns"),
    ("margin", "margen", "Common Nouns"),
    ("border", "frontera", "Common Nouns"),
    ("boundary", "limite", "Common Nouns"),
    ("limit", "limite", "Common Nouns"),
    ("barrier", "barrera", "Common Nouns"),
    ("wall", "pared / muro", "Common Nouns"),
    ("fence", "cerca", "Common Nouns"),
    ("gate", "porton", "Common Nouns"),
    ("door", "puerta", "Common Nouns"),
    ("window", "ventana", "Common Nouns"),
    ("glass", "vidrio", "Common Nouns"),
    ("mirror", "espejo", "Common Nouns"),
    ("reflection", "reflejo", "Common Nouns"),
    ("shadow", "sombra", "Common Nouns"),
    ("shade", "sombra", "Common Nouns"),
    ("sunlight", "luz solar", "Common Nouns"),
    ("sunshine", "luz del sol", "Common Nouns"),
    ("moonlight", "luz de luna", "Common Nouns"),
    ("starlight", "luz de estrellas", "Common Nouns"),
    ("dawn", "amanecer", "Common Nouns"),
    ("dusk", "anochecer", "Common Nouns"),
    ("twilight", "crepusculo", "Common Nouns"),
    ("sunrise", "amanecer", "Common Nouns"),
    ("sunset", "atardecer", "Common Nouns"),
    ("daylight", "luz del dia", "Common Nouns"),
    ("darkness", "oscuridad", "Common Nouns"),
    ("night", "noche", "Common Nouns"),
    ("midnight", "medianoche", "Common Nouns"),
    ("noon", "mediodia", "Common Nouns"),
    ("afternoon", "tarde", "Common Nouns"),
    ("evening", "tarde / noche", "Common Nouns"),
    ("morning", "manana", "Common Nouns"),
    ("dawn", "amanecer", "Common Nouns"),

    # ── 8. Numbers & Quantifiers (60 words) ───────────────────────────────
    ("zero", "cero", "Numbers & Quantifiers"),
    ("one", "uno", "Numbers & Quantifiers"),
    ("two", "dos", "Numbers & Quantifiers"),
    ("three", "tres", "Numbers & Quantifiers"),
    ("four", "cuatro", "Numbers & Quantifiers"),
    ("five", "cinco", "Numbers & Quantifiers"),
    ("six", "seis", "Numbers & Quantifiers"),
    ("seven", "siete", "Numbers & Quantifiers"),
    ("eight", "ocho", "Numbers & Quantifiers"),
    ("nine", "nueve", "Numbers & Quantifiers"),
    ("ten", "diez", "Numbers & Quantifiers"),
    ("eleven", "once", "Numbers & Quantifiers"),
    ("twelve", "doce", "Numbers & Quantifiers"),
    ("thirteen", "trece", "Numbers & Quantifiers"),
    ("fourteen", "catorce", "Numbers & Quantifiers"),
    ("fifteen", "quince", "Numbers & Quantifiers"),
    ("sixteen", "dieciseis", "Numbers & Quantifiers"),
    ("seventeen", "diecisiete", "Numbers & Quantifiers"),
    ("eighteen", "dieciocho", "Numbers & Quantifiers"),
    ("nineteen", "diecinueve", "Numbers & Quantifiers"),
    ("twenty", "veinte", "Numbers & Quantifiers"),
    ("thirty", "treinta", "Numbers & Quantifiers"),
    ("forty", "cuarenta", "Numbers & Quantifiers"),
    ("fifty", "cincuenta", "Numbers & Quantifiers"),
    ("sixty", "sesenta", "Numbers & Quantifiers"),
    ("seventy", "setenta", "Numbers & Quantifiers"),
    ("eighty", "ochenta", "Numbers & Quantifiers"),
    ("ninety", "noventa", "Numbers & Quantifiers"),
    ("hundred", "cien / ciento", "Numbers & Quantifiers"),
    ("thousand", "mil", "Numbers & Quantifiers"),
    ("million", "millon", "Numbers & Quantifiers"),
    ("billion", "mil millones", "Numbers & Quantifiers"),
    ("first", "primero", "Numbers & Quantifiers"),
    ("second", "segundo", "Numbers & Quantifiers"),
    ("third", "tercero", "Numbers & Quantifiers"),
    ("fourth", "cuarto", "Numbers & Quantifiers"),
    ("fifth", "quinto", "Numbers & Quantifiers"),
    ("last", "ultimo", "Numbers & Quantifiers"),
    ("half", "mitad", "Numbers & Quantifiers"),
    ("quarter", "cuarto / trimestre", "Numbers & Quantifiers"),
    ("third", "tercio", "Numbers & Quantifiers"),
    ("double", "doble", "Numbers & Quantifiers"),
    ("triple", "triple", "Numbers & Quantifiers"),
    ("single", "unico / individual", "Numbers & Quantifiers"),
    ("pair", "par", "Numbers & Quantifiers"),
    ("dozen", "docena", "Numbers & Quantifiers"),
    ("couple", "par / pareja", "Numbers & Quantifiers"),
    ("several", "varios", "Numbers & Quantifiers"),
    ("many", "muchos", "Numbers & Quantifiers"),
    ("much", "mucho", "Numbers & Quantifiers"),
    ("more", "mas", "Numbers & Quantifiers"),
    ("most", "la mayoria", "Numbers & Quantifiers"),
    ("few", "pocos", "Numbers & Quantifiers"),
    ("little", "poco", "Numbers & Quantifiers"),
    ("less", "menos", "Numbers & Quantifiers"),
    ("least", "el minimo", "Numbers & Quantifiers"),
    ("some", "algunos", "Numbers & Quantifiers"),
    ("any", "cualquier", "Numbers & Quantifiers"),
    ("all", "todos", "Numbers & Quantifiers"),
    ("none", "ninguno", "Numbers & Quantifiers"),

    # ── 9. Question Words & Expressions (50 words) ────────────────────────
    ("what", "que / cual", "Question Words"),
    ("who", "quien", "Question Words"),
    ("whom", "a quien", "Question Words"),
    ("whose", "de quien", "Question Words"),
    ("which", "cual", "Question Words"),
    ("where", "donde", "Question Words"),
    ("when", "cuando", "Question Words"),
    ("why", "por que", "Question Words"),
    ("how", "como", "Question Words"),
    ("how much", "cuanto (incontable)", "Question Words"),
    ("how many", "cuantos (contable)", "Question Words"),
    ("how often", "con que frecuencia", "Question Words"),
    ("how long", "cuanto tiempo", "Question Words"),
    ("how far", "que tan lejos", "Question Words"),
    ("how old", "cuantos anos", "Question Words"),
    ("how big", "que tan grande", "Question Words"),
    ("how tall", "que tan alto", "Question Words"),
    ("how wide", "que tan ancho", "Question Words"),
    ("how deep", "que tan profundo", "Question Words"),
    ("how heavy", "que tan pesado", "Question Words"),
    ("how fast", "que tan rapido", "Question Words"),
    ("how high", "que tan alto", "Question Words"),
    ("how wide", "que tan ancho", "Question Words"),
    ("how thick", "que tan grueso", "Question Words"),
    ("how strong", "que tan fuerte", "Question Words"),
    ("how long ago", "hace cuanto tiempo", "Question Words"),
    ("what kind of", "que tipo de", "Question Words"),
    ("what sort of", "que clase de", "Question Words"),
    ("what color", "de que color", "Question Words"),
    ("what size", "de que tamano", "Question Words"),
    ("what time", "a que hora", "Question Words"),
    ("what day", "que dia", "Question Words"),
    ("what date", "que fecha", "Question Words"),
    ("what month", "que mes", "Question Words"),
    ("what year", "que ano", "Question Words"),
    ("where from", "de donde", "Question Words"),
    ("where to", "hacia donde", "Question Words"),
    ("why not", "por que no", "Question Words"),
    ("how come", "como es que", "Question Words"),
    ("what about", "que hay de / que tal", "Question Words"),
    ("how about", "que tal / como acerca de", "Question Words"),
    ("what for", "para que", "Question Words"),
    ("who else", "quien mas", "Question Words"),
    ("what else", "que mas", "Question Words"),
    ("where else", "donde mas", "Question Words"),
    ("when else", "cuando mas", "Question Words"),
    ("how else", "como mas", "Question Words"),
    ("what if", "que si", "Question Words"),
    ("so what", "y que importa", "Question Words"),
    ("and then what", "y luego que", "Question Words"),

    # ── 10. Common Phrases (50 words) ─────────────────────────────────────
    ("of course", "por supuesto", "Common Phrases"),
    ("in fact", "de hecho", "Common Phrases"),
    ("at least", "al menos", "Common Phrases"),
    ("at most", "como maximo", "Common Phrases"),
    ("a lot of", "mucho / muchos", "Common Phrases"),
    ("lots of", "muchos / muchas", "Common Phrases"),
    ("instead of", "en lugar de", "Common Phrases"),
    ("because of", "debido a / por", "Common Phrases"),
    ("in front of", "enfrente de", "Common Phrases"),
    ("in back of", "detras de", "Common Phrases"),
    ("next to", "junto a / al lado de", "Common Phrases"),
    ("kind of", "tipo de / algo", "Common Phrases"),
    ("sort of", "tipo de / mas o menos", "Common Phrases"),
    ("out of", "fuera de", "Common Phrases"),
    ("kind of", "mas o menos", "Common Phrases"),
    ("as well as", "asi como / tambien", "Common Phrases"),
    ("as soon as", "tan pronto como", "Common Phrases"),
    ("as long as", "siempre y cuando", "Common Phrases"),
    ("as far as", "hasta donde / en cuanto a", "Common Phrases"),
    ("in order to", "para / con el fin de", "Common Phrases"),
    ("so as to", "para / con el fin de", "Common Phrases"),
    ("in spite of", "a pesar de", "Common Phrases"),
    ("regardless of", "sin importar", "Common Phrases"),
    ("on behalf of", "en nombre de", "Common Phrases"),
    ("in charge of", "a cargo de", "Common Phrases"),
    ("in case of", "en caso de", "Common Phrases"),
    ("by means of", "por medio de", "Common Phrases"),
    ("with regard to", "con respecto a", "Common Phrases"),
    ("in relation to", "en relacion a", "Common Phrases"),
    ("in addition to", "ademas de", "Common Phrases"),
    ("according to", "segun", "Common Phrases"),
    ("thanks to", "gracias a", "Common Phrases"),
    ("due to", "debido a", "Common Phrases"),
    ("apart from", "aparte de", "Common Phrases"),
    ("aside from", "aparte de", "Common Phrases"),
    ("rather than", "en lugar de", "Common Phrases"),
    ("other than", "distinto de / aparte de", "Common Phrases"),
    ("more than", "mas de", "Common Phrases"),
    ("less than", "menos de", "Common Phrases"),
    ("no more than", "no mas de", "Common Phrases"),
    ("no less than", "no menos de", "Common Phrases"),
    ("at least", "al menos", "Common Phrases"),
    ("at first", "al principio", "Common Phrases"),
    ("at last", "por fin / al fin", "Common Phrases"),
    ("at once", "de inmediato", "Common Phrases"),
    ("at present", "actualmente", "Common Phrases"),
    ("in general", "en general", "Common Phrases"),
    ("in particular", "en particular", "Common Phrases"),
    ("on purpose", "a proposito / intencionalmente", "Common Phrases"),
    ("by accident", "por accidente", "Common Phrases"),
]
# fmt: on


def seed_vocabulary(
    db: Session,
    word_list: list[tuple] | None = None,
) -> tuple[int, int]:
    """Upsert vocabulary words — insert new ones and update existing ones.

    Args:
        db: Database session.
        word_list: List of word tuples (english, spanish, category).
                   Defaults to the built-in VOCABULARY_WORDS list.

    Returns:
        (added, updated) counts.
    """
    from app.models import VocabularyWord

    words = VOCABULARY_WORDS if word_list is None else word_list

    added = updated = 0
    for english, spanish, category in words:
        existing = db.query(VocabularyWord).filter_by(english=english).first()
        if existing:
            existing.spanish = spanish
            existing.category = category
            updated += 1
        else:
            word = VocabularyWord(
                english=english,
                spanish=spanish,
                category=category,
            )
            db.add(word)
            added += 1

    db.commit()
    return added, updated
